### Instalación de requerimientos e importación de bibliotecas

In [ ]:
%pip install -r requirements.txt
import os
import gdown
import pandas as pd
import geopandas as gpd

import matplotlib.pyplot as plt
import contextily as ctx
import folium
import re

import polars as pl
from IPython.display import display

Requirement already satisfied: contextily in ./.venv/lib/python3.13/site-packages (from -r requirements.txt (line 1)) (1.7.0)
Requirement already satisfied: gdown in ./.venv/lib/python3.13/site-packages (from -r requirements.txt (line 2)) (6.1.0)
Requirement already satisfied: pandas in ./.venv/lib/python3.13/site-packages (from -r requirements.txt (line 3)) (3.0.3)
Requirement already satisfied: geopandas in ./.venv/lib/python3.13/site-packages (from -r requirements.txt (line 4)) (1.1.3)
Requirement already satisfied: matplotlib in ./.venv/lib/python3.13/site-packages (from -r requirements.txt (line 5)) (3.10.9)
Requirement already satisfied: folium in ./.venv/lib/python3.13/site-packages (from -r requirements.txt (line 7)) (0.20.0)
Requirement already satisfied: polars in ./.venv/lib/python3.13/site-packages (from -r requirements.txt (line 8)) (1.41.2)
Requirement already satisfied: fastexcel in ./.venv/lib/python3.13/site-packages (from -r requirements.txt (line 9)) (0.20.2)
Requirement already satisfied: geopy in ./.venv/lib/python3.13/site-packages (from contextily->-r requirements.txt (line 1)) (2.4.1)
Requirement already satisfied: mercantile in ./.venv/lib/python3.13/site-packages (from contextily->-r requirements.txt (line 1)) (1.2.1)
Requirement already satisfied: pillow in ./.venv/lib/python3.13/site-packages (from contextily->-r requirements.txt (line 1)) (12.2.0)
Requirement already satisfied: rasterio in ./.venv/lib/python3.13/site-packages (from contextily->-r requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: requests in ./.venv/lib/python3.13/site-packages (from contextily->-r requirements.txt (line 1)) (2.34.2)
Requirement already satisfied: joblib in ./.venv/lib/python3.13/site-packages (from contextily->-r requirements.txt (line 1)) (1.5.3)
Requirement already satisfied: xyzservices in ./.venv/lib/python3.13/site-packages (from contextily->-r requirements.txt (line 1)) (2026.3.0)
Requirement already satisfied: beautifulsoup4 in ./.venv/lib/python3.13/site-packages (from gdown->-r requirements.txt (line 2)) (4.14.3)
Requirement already satisfied: filelock in ./.venv/lib/python3.13/site-packages (from gdown->-r requirements.txt (line 2)) (3.29.1)
Requirement already satisfied: tqdm in ./.venv/lib/python3.13/site-packages (from gdown->-r requirements.txt (line 2)) (4.68.1)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.13/site-packages (from pandas->-r requirements.txt (line 3)) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas->-r requirements.txt (line 3)) (2.9.0.post0)
Requirement already satisfied: pyogrio>=0.7.2 in ./.venv/lib/python3.13/site-packages (from geopandas->-r requirements.txt (line 4)) (0.12.1)
Requirement already satisfied: packaging in ./.venv/lib/python3.13/site-packages (from geopandas->-r requirements.txt (line 4)) (26.2)
Requirement already satisfied: pyproj>=3.5.0 in ./.venv/lib/python3.13/site-packages (from geopandas->-r requirements.txt (line 4)) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in ./.venv/lib/python3.13/site-packages (from geopandas->-r requirements.txt (line 4)) (2.1.2)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 5)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 5)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 5)) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 5)) (1.5.0)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 5)) (3.3.2)
Requirement already satisfied: branca>=0.6.0 in ./.venv/lib/python3.13/site-packages (from folium->-r requirements.txt (line 7)) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in ./.venv/lib/python3.13/site-packages (from folium->-r requirements.txt (line 7)) (3.1.6)
Requirement already satisfied: polars-runtime-32==1.41.2 in ./.venv/lib/python3.13/site-packages (from polars->-r requirements.txt (line 8)) (1.41.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.13/site-packages (from jinja2>=2.9->folium->-r requirements.txt (line 7)) (3.0.3)
Requirement already satisfied: certifi in ./.venv/lib/python3.13/site-packages (from pyogrio>=0.7.2->geopandas->-r requirements.txt (line 4)) (2026.5.20)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 3)) (1.17.0)
Requirement already satisfied: soupsieve>=1.6.1 in ./.venv/lib/python3.13/site-packages (from beautifulsoup4->gdown->-r requirements.txt (line 2)) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in ./.venv/lib/python3.13/site-packages (from beautifulsoup4->gdown->-r requirements.txt (line 2)) (4.15.0)
Requirement already satisfied: geographiclib<3,>=1.52 in ./.venv/lib/python3.13/site-packages (from geopy->contextily->-r requirements.txt (line 1)) (2.1)
Requirement already satisfied: click>=3.0 in ./.venv/lib/python3.13/site-packages (from mercantile->contextily->-r requirements.txt (line 1)) (8.4.1)
Requirement already satisfied: affine in ./.venv/lib/python3.13/site-packages (from rasterio->contextily->-r requirements.txt (line 1)) (2.4.0)
Requirement already satisfied: attrs in ./.venv/lib/python3.13/site-packages (from rasterio->contextily->-r requirements.txt (line 1)) (26.1.0)
Requirement already satisfied: cligj>=0.5 in ./.venv/lib/python3.13/site-packages (from rasterio->contextily->-r requirements.txt (line 1)) (0.7.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.13/site-packages (from requests->contextily->-r requirements.txt (line 1)) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.13/site-packages (from requests->contextily->-r requirements.txt (line 1)) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.13/site-packages (from requests->contextily->-r requirements.txt (line 1)) (2.7.0)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in ./.venv/lib/python3.13/site-packages (from requests[socks]->gdown->-r requirements.txt (line 2)) (1.7.1)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

### Función para descarga de datasets con gdown

In [2]:
# URL de Google Drive
url = "https://drive.google.com/uc?id=ID_DEL_ARCHIVO"

def descargar_archivos_desde_drive(lista_ids):
    """
    Descarga varios archivos de Google Drive a partir de una lista de IDs.

    Args:
        lista_ids (list): Una lista de strings con los IDs de los archivos de Drive.
    """
    for file_id in lista_ids:
        # Construimos la URL de descarga directa
        url = f'https://drive.google.com/uc?id={file_id}'

        print(f"\nIniciando descarga del ID: {file_id}")

        try:
            # gdown detecta automáticamente el nombre original del archivo
            gdown.download(url, quiet=False)
        except Exception as e:
            print(f"No se pudo descargar el archivo {file_id}. Error: {e}")

In [3]:
# Definir la carpeta y el archivo de destino
output_dir = "./content/csv"

# Crear la carpeta si no existe
os.makedirs(output_dir, exist_ok=True)

# Se cambia a la carpeta de descaga de CSV
os.chdir(output_dir)

### Carga de CSV desde Google Drive

In [4]:
'''

lista_ids_datasets = [
    '1sWI3jP6f9VDJ-IE1EI1lkc8rkxooP3b7', # lineas-de-subte
    '1V6Cjhf2QU_gcig6HT5EvXhk0n2Egerqr', # estaciones-accesibles
    '1CyWPBgfAYRBcYvQO7U7cRlAoQbGWoosP', # historico_2014
    '1g7LpNJFqNcqDmgaGc81MMgV3VfrD6Ah6', # historico_2015
    '1QqOb3oLoMs014d2YBYw4_e8ww4jo-JX1', # historico_2016
    '1G7noINplTWyt2g9xRrS7l0BKgFOW05hv', # historico_2017
    '11WgJxZsC4zUURSlCUBEQKXCQK5RLkRNZ', # historico_2018
    '1DVgvubSgYCTPQCfA4zj5eiH_ni136o9A', # historico_2019
    '1hlfAVsJS20InzvIkUXT4t5_nOgd2m1NW', # historico_2020
    '1hW4qHioTzrXlDnBfWextpMQpar0kmL03', # historico_2021
    '1yETNbct23DLqYoN7ti6hNV3RdKErwMYI', # registro-historico-del-precio-del-boleto
    '1mY28zAPaI79Pt-OLoNSAhIxnCtflpmKU', # registro-historico-del-precio-del-boleto.xlsx
    '1PEAW6Vik2k-J7k9C6gxNtl_2df636Q41'  # viajes_anual
    ]

descargar_archivos_desde_drive(lista_ids_datasets)
'''

"\n\nlista_ids_datasets = [\n    '1sWI3jP6f9VDJ-IE1EI1lkc8rkxooP3b7', # lineas-de-subte\n    '1V6Cjhf2QU_gcig6HT5EvXhk0n2Egerqr', # estaciones-accesibles\n    '1CyWPBgfAYRBcYvQO7U7cRlAoQbGWoosP', # historico_2014\n    '1g7LpNJFqNcqDmgaGc81MMgV3VfrD6Ah6', # historico_2015\n    '1QqOb3oLoMs014d2YBYw4_e8ww4jo-JX1', # historico_2016\n    '1G7noINplTWyt2g9xRrS7l0BKgFOW05hv', # historico_2017\n    '11WgJxZsC4zUURSlCUBEQKXCQK5RLkRNZ', # historico_2018\n    '1DVgvubSgYCTPQCfA4zj5eiH_ni136o9A', # historico_2019\n    '1hlfAVsJS20InzvIkUXT4t5_nOgd2m1NW', # historico_2020\n    '1hW4qHioTzrXlDnBfWextpMQpar0kmL03', # historico_2021\n    '1yETNbct23DLqYoN7ti6hNV3RdKErwMYI', # registro-historico-del-precio-del-boleto\n    '1mY28zAPaI79Pt-OLoNSAhIxnCtflpmKU', # registro-historico-del-precio-del-boleto.xlsx\n    '1PEAW6Vik2k-J7k9C6gxNtl_2df636Q41'  # viajes_anual\n    ]\n\ndescargar_archivos_desde_drive(lista_ids_datasets)\n"

### Carga de CSV en dataframes de Polars (columnar)

In [5]:
# Se cargan archivos en dataframes de polars
# Se agrega el encoding latin 1 para evitar errores

null_values = ["NA", "N/A", ""]

lineas_subte_df = pl.read_csv('lineas-de-subte.csv', encoding='latin-1', null_values=null_values)

estaciones_accesibles_df = pl.read_csv('estaciones-accesibles.csv', encoding='latin-1', null_values=null_values)

historico_2014_df = pl.read_csv('historico_2014.csv', encoding='latin-1', null_values=null_values)
historico_2015_df = pl.read_csv('historico_2015.csv', encoding='latin-1', null_values=null_values)
historico_2016_df = pl.read_csv('historico_2016.csv', encoding='latin-1', null_values=null_values)
historico_2017_df = pl.read_csv('historico_2017.csv', encoding='latin-1', null_values=null_values)
historico_2018_df = pl.read_csv('historico_2018.csv', encoding='latin-1', null_values=null_values)
historico_2019_df = pl.read_csv('historico_2019.csv', encoding='latin-1', null_values=null_values)
historico_2020_df = pl.read_csv('historico_2020.csv', encoding='latin-1', null_values=null_values)
historico_2021_df = pl.read_csv('historico_2021.csv', encoding='latin-1', null_values=null_values, separator=';')
registro_historico_del_precio_del_boleto_df = pl.read_csv('registro-historico-del-precio-del-boleto.csv', encoding='latin-1', null_values=null_values)
registro_historico_del_precio_del_boleto_excel_df = pl.read_excel('registro-historico-del-precio-del-boleto.xlsx')
viajes_anual_df = pl.read_csv('viajes_anual.csv', encoding='latin-1', null_values=null_values)

### Análisis exploratorio de los dataframes

In [6]:
print("lineas_subte - Column names ", lineas_subte_df.columns)
display(lineas_subte_df.head())

print ('\n\n---------------------\n\n')

print("estaciones_accesibles - Column names:", estaciones_accesibles_df.columns)
display(estaciones_accesibles_df.head())

print ('\n\n---------------------\n\n')
print("historico_2014 - Column names:", historico_2014_df.columns)
display(historico_2014_df.head())

print ('\n\n---------------------\n\n')

print("historico_2015 - Column names:", historico_2015_df.columns)
display(historico_2015_df.head())

print ('\n\n---------------------\n\n')

print("historico_2016 - Column names:", historico_2016_df.columns)
display(historico_2016_df.head())

print ('\n\n---------------------\n\n')

print("historico_2017 - Column names:", historico_2017_df.columns)
display(historico_2017_df.head())

print ('\n\n---------------------\n\n')

print("historico_2018 - Column names:", historico_2018_df.columns)
display(historico_2018_df.head())

print ('\n\n---------------------\n\n')

print("historico_2019 - Column names:", historico_2019_df.columns)
display(historico_2019_df.head())

print ('\n\n---------------------\n\n')

print("historico_2020 - Column names:", historico_2020_df.columns)
display(historico_2020_df.head())

print ('\n\n---------------------\n\n')

print("historico_2021 - Column names:", historico_2021_df.columns)
display(historico_2021_df.head())

print ('\n\n---------------------\n\n')

lineas_subte - Column names  ['wkt', 'id', 'lineasub']

shape: (5, 3)
┌─────────────────────────────────┬─────┬──────────┐
│ wkt                             ┆ id  ┆ lineasub │
│ ---                             ┆ --- ┆ ---      │
│ str                             ┆ i64 ┆ str      │
╞═════════════════════════════════╪═════╪══════════╡
│ MULTILINESTRING ((-58.45212560… ┆ 1   ┆ LINEA D  │
│ MULTILINESTRING ((-58.45648913… ┆ 2   ┆ LINEA D  │
│ MULTILINESTRING ((-58.44466814… ┆ 3   ┆ LINEA D  │
│ MULTILINESTRING ((-58.43501353… ┆ 4   ┆ LINEA D  │
│ MULTILINESTRING ((-58.42571144… ┆ 5   ┆ LINEA D  │
└─────────────────────────────────┴─────┴──────────┘

---------------------


estaciones_accesibles - Column names: ['long', 'lat', 'linea', 'estacion', 'escaleras_mecanicas', 'ascensores']

shape: (5, 6)
┌────────────┬────────────┬───────┬───────────────┬─────────────────────┬────────────┐
│ long       ┆ lat        ┆ linea ┆ estacion      ┆ escaleras_mecanicas ┆ ascensores │
│ ---        ┆ ---        ┆ ---   ┆ ---           ┆ ---                 ┆ ---        │
│ f64        ┆ f64        ┆ str   ┆ str           ┆ i64                 ┆ i64        │
╞════════════╪════════════╪═══════╪═══════════════╪═════════════════════╪════════════╡
│ -58.436429 ┆ -34.61828  ┆ A     ┆ ACOYTE        ┆ 2                   ┆ 2          │
│ -58.45671  ┆ -34.626667 ┆ A     ┆ CARABOBO      ┆ 3                   ┆ 3          │
│ -58.421816 ┆ -34.61177  ┆ A     ┆ CASTRO BARROS ┆ 1                   ┆ 1          │
│ -58.392669 ┆ -34.609226 ┆ A     ┆ CONGRESO      ┆ 2                   ┆ 2          │
│ -58.382232 ┆ -34.6091   ┆ A     ┆ LIMA          ┆ 1                   ┆ 0          │
└────────────┴────────────┴───────┴───────────────┴─────────────────────┴────────────┘

---------------------


historico_2014 - Column names: ['FECHA', 'DESDE', 'HASTA', 'LINEA', 'MOLINETE', 'ID_ESTACION', 'ESTACION', 'PAX_PAGO', 'PAX_PASES_PAGOS', 'PAX_FRANQ', 'PAX_TOTAL']

shape: (5, 11)
┌────────────┬──────────┬──────────┬───────┬───┬──────────┬────────────────┬───────────┬───────────┐
│ FECHA      ┆ DESDE    ┆ HASTA    ┆ LINEA ┆ … ┆ PAX_PAGO ┆ PAX_PASES_PAGO ┆ PAX_FRANQ ┆ PAX_TOTAL │
│ ---        ┆ ---      ┆ ---      ┆ ---   ┆   ┆ ---      ┆ S              ┆ ---       ┆ ---       │
│ str        ┆ str      ┆ str      ┆ str   ┆   ┆ i64      ┆ ---            ┆ i64       ┆ i64       │
│            ┆          ┆          ┆       ┆   ┆          ┆ i64            ┆           ┆           │
╞════════════╪══════════╪══════════╪═══════╪═══╪══════════╪════════════════╪═══════════╪═══════════╡
│ 2014-04-09 ┆ 09:15:00 ┆ 09:29:00 ┆ B     ┆ … ┆ 7        ┆ null           ┆ null      ┆ 7         │
│ 2014-04-09 ┆ 09:15:00 ┆ 09:29:00 ┆ B     ┆ … ┆ 9        ┆ null           ┆ null      ┆ 9         │
│ 2014-04-09 ┆ 09:15:00 ┆ 09:29:00 ┆ B     ┆ … ┆ 14       ┆ null           ┆ 2         ┆ 16        │
│ 2014-04-09 ┆ 09:15:00 ┆ 09:29:00 ┆ B     ┆ … ┆ 18       ┆ null           ┆ null      ┆ 18        │
│ 2014-04-09 ┆ 09:15:00 ┆ 09:29:00 ┆ B     ┆ … ┆ 12       ┆ null           ┆ null      ┆ 12        │
└────────────┴──────────┴──────────┴───────┴───┴──────────┴────────────────┴───────────┴───────────┘

---------------------


historico_2015 - Column names: ['periodo', 'fecha', 'desde', 'hasta', 'linea', 'molinete', 'estacion', 'pax_pagos', 'pax_pases_pagos', 'pax_franq', 'total']

shape: (5, 11)
┌─────────┬────────────┬──────────┬──────────┬───┬───────────┬─────────────────┬───────────┬───────┐
│ periodo ┆ fecha      ┆ desde    ┆ hasta    ┆ … ┆ pax_pagos ┆ pax_pases_pagos ┆ pax_franq ┆ total │
│ ---     ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---             ┆ ---       ┆ ---   │
│ i64     ┆ str        ┆ str      ┆ str      ┆   ┆ f64       ┆ f64             ┆ f64       ┆ f64   │
╞═════════╪════════════╪══════════╪══════════╪═══╪═══════════╪═════════════════╪═══════════╪═══════╡
│ 201501  ┆ 2015-01-01 ┆ 05:00:00 ┆ 05:15:00 ┆ … ┆ 0.0       ┆ 0.0             ┆ 0.0       ┆ 0.0   │
│ 201501  ┆ 2015-01-01 ┆ 05:30:00 ┆ 05:45:00 ┆ … ┆ 0.0       ┆ 0.0             ┆ 0.0       ┆ 0.0   │
│ 201501  ┆ 2015-01-01 ┆ 05:30:00 ┆ 05:45:00 ┆ … ┆ 0.0       ┆ 0.0             ┆ 0.0       ┆ 0.0   │
│ 201501  ┆ 2015-01-01 ┆ 05:30:00 ┆ 05:45:00 ┆ … ┆ 0.0       ┆ 0.0             ┆ 0.0       ┆ 0.0   │
│ 201501  ┆ 2015-01-01 ┆ 06:00:00 ┆ 06:15:00 ┆ … ┆ 0.0       ┆ 0.0             ┆ 0.0       ┆ 0.0   │
└─────────┴────────────┴──────────┴──────────┴───┴───────────┴─────────────────┴───────────┴───────┘

---------------------


historico_2016 - Column names: ['FECHA', 'DESDE', 'HASTA', 'LINEA', 'MOLINETE', 'ID_ESTACION', 'ESTACION', 'PAX_PAGOS', 'PAX_PASES_PAGOS', 'PAX_FREQ', 'TOTAL']

shape: (5, 11)
┌────────────┬──────────┬──────────┬───────┬───┬───────────┬─────────────────┬──────────┬───────┐
│ FECHA      ┆ DESDE    ┆ HASTA    ┆ LINEA ┆ … ┆ PAX_PAGOS ┆ PAX_PASES_PAGOS ┆ PAX_FREQ ┆ TOTAL │
│ ---        ┆ ---      ┆ ---      ┆ ---   ┆   ┆ ---       ┆ ---             ┆ ---      ┆ ---   │
│ str        ┆ str      ┆ str      ┆ str   ┆   ┆ i64       ┆ i64             ┆ i64      ┆ i64   │
╞════════════╪══════════╪══════════╪═══════╪═══╪═══════════╪═════════════════╪══════════╪═══════╡
│ 02/01/2016 ┆ 05:00:00 ┆ 05:15:00 ┆ D     ┆ … ┆ 1         ┆ 0               ┆ 0        ┆ 1     │
│ 02/01/2016 ┆ 05:00:00 ┆ 05:15:00 ┆ D     ┆ … ┆ 2         ┆ 0               ┆ 0        ┆ 2     │
│ 05/01/2016 ┆ 05:00:00 ┆ 05:15:00 ┆ D     ┆ … ┆ 1         ┆ 0               ┆ 0        ┆ 1     │
│ 06/01/2016 ┆ 05:00:00 ┆ 05:15:00 ┆ D     ┆ … ┆ 2         ┆ 0               ┆ 0        ┆ 2     │
│ 06/01/2016 ┆ 05:00:00 ┆ 05:15:00 ┆ D     ┆ … ┆ 1         ┆ 0               ┆ 0        ┆ 1     │
└────────────┴──────────┴──────────┴───────┴───┴───────────┴─────────────────┴──────────┴───────┘

---------------------


historico_2017 - Column names: ['V1', 'FECHA', 'DESDE', 'HASTA', 'LINEA', 'MOLINETE', 'ID_ESTACION', 'ESTACION', 'PAX_PAGOS', 'PAX_PASES_PAGOS', 'PAX_FREQ', 'TOTAL']

shape: (5, 12)
┌─────┬────────────┬──────────┬──────────┬───┬───────────┬─────────────────┬──────────┬───────┐
│ V1  ┆ FECHA      ┆ DESDE    ┆ HASTA    ┆ … ┆ PAX_PAGOS ┆ PAX_PASES_PAGOS ┆ PAX_FREQ ┆ TOTAL │
│ --- ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---             ┆ ---      ┆ ---   │
│ i64 ┆ str        ┆ str      ┆ str      ┆   ┆ i64       ┆ i64             ┆ i64      ┆ i64   │
╞═════╪════════════╪══════════╪══════════╪═══╪═══════════╪═════════════════╪══════════╪═══════╡
│ 1   ┆ 01/01/2017 ┆ 08:00:00 ┆ 08:15:00 ┆ … ┆ 1         ┆ 0               ┆ 0        ┆ 1     │
│ 2   ┆ 01/01/2017 ┆ 08:00:00 ┆ 08:15:00 ┆ … ┆ 1         ┆ 0               ┆ 0        ┆ 1     │
│ 3   ┆ 01/01/2017 ┆ 08:00:00 ┆ 08:15:00 ┆ … ┆ 1         ┆ 0               ┆ 0        ┆ 1     │
│ 4   ┆ 01/01/2017 ┆ 08:15:00 ┆ 08:30:00 ┆ … ┆ 1         ┆ 0               ┆ 0        ┆ 1     │
│ 5   ┆ 01/01/2017 ┆ 08:15:00 ┆ 08:30:00 ┆ … ┆ 2         ┆ 0               ┆ 0        ┆ 2     │
└─────┴────────────┴──────────┴──────────┴───┴───────────┴─────────────────┴──────────┴───────┘

---------------------


historico_2018 - Column names: ['fecha', 'desde', 'hasta', 'linea', 'molinete', 'estacion', 'pax_pagos', 'pax_pases_pagos', 'pax_franq', 'total', 'periodo']

shape: (5, 11)
┌────────────┬──────────┬──────────┬────────┬───┬─────────────────┬───────────┬───────┬─────────┐
│ fecha      ┆ desde    ┆ hasta    ┆ linea  ┆ … ┆ pax_pases_pagos ┆ pax_franq ┆ total ┆ periodo │
│ ---        ┆ ---      ┆ ---      ┆ ---    ┆   ┆ ---             ┆ ---       ┆ ---   ┆ ---     │
│ str        ┆ str      ┆ str      ┆ str    ┆   ┆ f64             ┆ f64       ┆ f64   ┆ i64     │
╞════════════╪══════════╪══════════╪════════╪═══╪═════════════════╪═══════════╪═══════╪═════════╡
│ 2018-01-01 ┆ 08:00:00 ┆ 08:15:00 ┆ LineaA ┆ … ┆ 0.0             ┆ 0.0       ┆ 1.0   ┆ 201801  │
│ 2018-01-01 ┆ 08:00:00 ┆ 08:15:00 ┆ LineaA ┆ … ┆ 0.0             ┆ 0.0       ┆ 4.0   ┆ 201801  │
│ 2018-01-01 ┆ 08:00:00 ┆ 08:15:00 ┆ LineaA ┆ … ┆ 0.0             ┆ 0.0       ┆ 1.0   ┆ 201801  │
│ 2018-01-01 ┆ 08:00:00 ┆ 08:15:00 ┆ LineaA ┆ … ┆ 0.0             ┆ 0.0       ┆ 4.0   ┆ 201801  │
│ 2018-01-01 ┆ 08:00:00 ┆ 08:15:00 ┆ LineaA ┆ … ┆ 0.0             ┆ 0.0       ┆ 2.0   ┆ 201801  │
└────────────┴──────────┴──────────┴────────┴───┴─────────────────┴───────────┴───────┴─────────┘

---------------------


historico_2019 - Column names: ['periodo', 'fecha', 'desde', 'hasta', 'linea', 'molinete', 'estacion', 'pax_pagos', 'pax_pases_pagos', 'pax_franq', 'total']

shape: (5, 11)
┌─────────┬────────────┬──────────┬──────────┬───┬───────────┬─────────────────┬───────────┬───────┐
│ periodo ┆ fecha      ┆ desde    ┆ hasta    ┆ … ┆ pax_pagos ┆ pax_pases_pagos ┆ pax_franq ┆ total │
│ ---     ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---             ┆ ---       ┆ ---   │
│ i64     ┆ str        ┆ str      ┆ str      ┆   ┆ f64       ┆ f64             ┆ f64       ┆ f64   │
╞═════════╪════════════╪══════════╪══════════╪═══╪═══════════╪═════════════════╪═══════════╪═══════╡
│ 201901  ┆ 2019-01-01 ┆ 08:00:00 ┆ 08:15:00 ┆ … ┆ 1.0       ┆ 0.0             ┆ 0.0       ┆ 1.0   │
│ 201901  ┆ 2019-01-01 ┆ 08:00:00 ┆ 08:15:00 ┆ … ┆ 3.0       ┆ 0.0             ┆ 0.0       ┆ 3.0   │
│ 201901  ┆ 2019-01-01 ┆ 08:00:00 ┆ 08:15:00 ┆ … ┆ 3.0       ┆ 0.0             ┆ 0.0       ┆ 3.0   │
│ 201901  ┆ 2019-01-01 ┆ 08:00:00 ┆ 08:15:00 ┆ … ┆ 6.0       ┆ 0.0             ┆ 0.0       ┆ 6.0   │
│ 201901  ┆ 2019-01-01 ┆ 08:00:00 ┆ 08:15:00 ┆ … ┆ 10.0      ┆ 0.0             ┆ 0.0       ┆ 10.0  │
└─────────┴────────────┴──────────┴──────────┴───┴───────────┴─────────────────┴───────────┴───────┘

---------------------


historico_2020 - Column names: ['FECHA', 'DESDE', 'HASTA', 'LINEA', 'MOLINETE', 'ESTACION', 'pax_pagos', 'pax_pases_pagos', 'pax_franq', 'pax_TOTAL']

shape: (5, 10)
┌────────────┬──────────┬──────────┬────────┬───┬───────────┬──────────────┬───────────┬───────────┐
│ FECHA      ┆ DESDE    ┆ HASTA    ┆ LINEA  ┆ … ┆ pax_pagos ┆ pax_pases_pa ┆ pax_franq ┆ pax_TOTAL │
│ ---        ┆ ---      ┆ ---      ┆ ---    ┆   ┆ ---       ┆ gos          ┆ ---       ┆ ---       │
│ str        ┆ str      ┆ str      ┆ str    ┆   ┆ i64       ┆ ---          ┆ i64       ┆ i64       │
│            ┆          ┆          ┆        ┆   ┆           ┆ i64          ┆           ┆           │
╞════════════╪══════════╪══════════╪════════╪═══╪═══════════╪══════════════╪═══════════╪═══════════╡
│ 01/01/2020 ┆ 08:00:00 ┆ 08:15:00 ┆ LineaA ┆ … ┆ 1         ┆ 0            ┆ 0         ┆ 1         │
│ 01/01/2020 ┆ 08:00:00 ┆ 08:15:00 ┆ LineaA ┆ … ┆ 6         ┆ 0            ┆ 0         ┆ 6         │
│ 01/01/2020 ┆ 08:00:00 ┆ 08:15:00 ┆ LineaA ┆ … ┆ 3         ┆ 0            ┆ 1         ┆ 4         │
│ 01/01/2020 ┆ 08:00:00 ┆ 08:15:00 ┆ LineaA ┆ … ┆ 2         ┆ 0            ┆ 0         ┆ 2         │
│ 01/01/2020 ┆ 08:00:00 ┆ 08:15:00 ┆ LineaA ┆ … ┆ 2         ┆ 0            ┆ 0         ┆ 2         │
└────────────┴──────────┴──────────┴────────┴───┴───────────┴──────────────┴───────────┴───────────┘

---------------------


historico_2021 - Column names: ['periodo', 'FECHA', 'DESDE', 'HASTA', 'LINEA', 'MOLINETE', 'ESTACION', 'pax_pagos', 'pax_pases_pagos', 'pax_franq', 'pax_TOTAL']

shape: (5, 11)
┌─────────┬──────────┬──────────┬──────────┬───┬───────────┬───────────────┬───────────┬───────────┐
│ periodo ┆ FECHA    ┆ DESDE    ┆ HASTA    ┆ … ┆ pax_pagos ┆ pax_pases_pag ┆ pax_franq ┆ pax_TOTAL │
│ ---     ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ os            ┆ ---       ┆ ---       │
│ i64     ┆ str      ┆ str      ┆ str      ┆   ┆ i64       ┆ ---           ┆ i64       ┆ i64       │
│         ┆          ┆          ┆          ┆   ┆           ┆ i64           ┆           ┆           │
╞═════════╪══════════╪══════════╪══════════╪═══╪═══════════╪═══════════════╪═══════════╪═══════════╡
│ 2021    ┆ 1/1/2021 ┆ 08:00:00 ┆ 08:15:00 ┆ … ┆ 1         ┆ 0             ┆ 0         ┆ 1         │
│ 2021    ┆ 1/1/2021 ┆ 08:00:00 ┆ 08:15:00 ┆ … ┆ 0         ┆ 0             ┆ 2         ┆ 2         │
│ 2021    ┆ 1/1/2021 ┆ 08:00:00 ┆ 08:15:00 ┆ … ┆ 1         ┆ 0             ┆ 0         ┆ 1         │
│ 2021    ┆ 1/1/2021 ┆ 08:00:00 ┆ 08:15:00 ┆ … ┆ 1         ┆ 0             ┆ 0         ┆ 1         │
│ 2021    ┆ 1/1/2021 ┆ 08:00:00 ┆ 08:15:00 ┆ … ┆ 1         ┆ 0             ┆ 0         ┆ 1         │
└─────────┴──────────┴──────────┴──────────┴───┴───────────┴───────────────┴───────────┴───────────┘

---------------------

### Exploración de estaciones accesibles sin escaleras mecánicas ni ascensores

In [7]:
# Filtramos usando .filter() y expresiones pl.col
resultado_df = estaciones_accesibles_df.filter(
    (pl.col("escaleras_mecanicas") == 0) & (pl.col("ascensores") == 0)
)

# Lo mostrás directamente (acordate que no hace falta display si es lo último)
resultado_df

shape: (0, 6)
┌──────┬─────┬───────┬──────────┬─────────────────────┬────────────┐
│ long ┆ lat ┆ linea ┆ estacion ┆ escaleras_mecanicas ┆ ascensores │
│ ---  ┆ --- ┆ ---   ┆ ---      ┆ ---                 ┆ ---        │
│ f64  ┆ f64 ┆ str   ┆ str      ┆ i64                 ┆ i64        │
╞══════╪═════╪═══════╪══════════╪═════════════════════╪════════════╡
└──────┴─────┴───────┴──────────┴─────────────────────┴────────────┘

### Observaciones

Se observa que no hay estaciones listadas como estaciones accesibles que posean 0 escaleras mecánicas y 0 ascensores, lo cual es correcto.

### Nulos

Al planificar el análisis predictivo con Prophet, no es necesario explorar o modificar los campos nulos en los campos numéricos. Se realiza el análisis en los campos literales para revisar que las etiquetas estén correctas y no cortar la continuidad de los datos.

In [12]:
# --- CONFIGURACIÓN DE VISUALIZACIÓN CORRECTA ---
# Forzamos a que no mutile los nombres de texto largos en la consola
pl.Config.set_tbl_rows(100)
pl.Config.set_fmt_str_lengths(100)

for anio in range(2014, 2022):
    nombre_var = f"historico_{anio}_df"
    
    # Verificamos si el DataFrame realmente existe en la memoria antes de procesarlo
    if nombre_var in globals():
        # Traemos el DataFrame usando su nombre en texto
        df_actual = globals()[nombre_var]
        
        # Ejecutamos el reporte de nulos y vacíos en formato vertical
        reporte = df_actual.select([
            pl.all().null_count().name.suffix("_nulos"),
            (pl.col(pl.String).str.strip_chars() == "").sum().name.suffix("_vacios")
        ]).transpose(include_header=True, header_name="Columna_Métrica", column_names=["Cantidad"])        
        
        # Imprimimos un encabezado claro para cada año
        print(f"=== REPORTE DE CALIDAD VIRTICAL: HISTORICO {anio} ===")
        print(reporte)
        print("-" * 50, "\n")
    else:
        print(f"⚠️ La variable {nombre_var} no está cargada en el entorno.\n")

=== REPORTE DE CALIDAD VIRTICAL: HISTORICO 2014 ===
shape: (17, 2)
┌───────────────────────┬──────────┐
│ Columna_Métrica       ┆ Cantidad │
│ ---                   ┆ ---      │
│ str                   ┆ u32      │
╞═══════════════════════╪══════════╡
│ FECHA_nulos           ┆ 0        │
│ DESDE_nulos           ┆ 0        │
│ HASTA_nulos           ┆ 0        │
│ LINEA_nulos           ┆ 0        │
│ MOLINETE_nulos        ┆ 0        │
│ ID_ESTACION_nulos     ┆ 364840   │
│ ESTACION_nulos        ┆ 0        │
│ PAX_PAGO_nulos        ┆ 190965   │
│ PAX_PASES_PAGOS_nulos ┆ 8767900  │
│ PAX_FRANQ_nulos       ┆ 4516732  │
│ PAX_TOTAL_nulos       ┆ 0        │
│ FECHA_vacios          ┆ 0        │
│ DESDE_vacios          ┆ 0        │
│ HASTA_vacios          ┆ 0        │
│ LINEA_vacios          ┆ 0        │
│ MOLINETE_vacios       ┆ 0        │
│ ESTACION_vacios       ┆ 0        │
└───────────────────────┴──────────┘
--------------------------------------------------

=== REPORTE DE CALIDAD VIRTICAL: HISTORICO 2015 ===
shape: (17, 2)
┌───────────────────────┬──────────┐
│ Columna_Métrica       ┆ Cantidad │
│ ---                   ┆ ---      │
│ str                   ┆ u32      │
╞═══════════════════════╪══════════╡
│ periodo_nulos         ┆ 0        │
│ fecha_nulos           ┆ 0        │
│ desde_nulos           ┆ 0        │
│ hasta_nulos           ┆ 0        │
│ linea_nulos           ┆ 0        │
│ molinete_nulos        ┆ 0        │
│ estacion_nulos        ┆ 0        │
│ pax_pagos_nulos       ┆ 0        │
│ pax_pases_pagos_nulos ┆ 0        │
│ pax_franq_nulos       ┆ 0        │
│ total_nulos           ┆ 0        │
│ fecha_vacios          ┆ 0        │
│ desde_vacios          ┆ 0        │
│ hasta_vacios          ┆ 0        │
│ linea_vacios          ┆ 0        │
│ molinete_vacios       ┆ 0        │
│ estacion_vacios       ┆ 0        │
└───────────────────────┴──────────┘
--------------------------------------------------

=== REPORTE DE CALIDAD VIRTICAL: HISTORICO 2016 ===
shape: (17, 2)
┌───────────────────────┬──────────┐
│ Columna_Métrica       ┆ Cantidad │
│ ---                   ┆ ---      │
│ str                   ┆ u32      │
╞═══════════════════════╪══════════╡
│ FECHA_nulos           ┆ 0        │
│ DESDE_nulos           ┆ 0        │
│ HASTA_nulos           ┆ 0        │
│ LINEA_nulos           ┆ 0        │
│ MOLINETE_nulos        ┆ 0        │
│ ID_ESTACION_nulos     ┆ 3812106  │
│ ESTACION_nulos        ┆ 0        │
│ PAX_PAGOS_nulos       ┆ 0        │
│ PAX_PASES_PAGOS_nulos ┆ 0        │
│ PAX_FREQ_nulos        ┆ 0        │
│ TOTAL_nulos           ┆ 0        │
│ FECHA_vacios          ┆ 0        │
│ DESDE_vacios          ┆ 0        │
│ HASTA_vacios          ┆ 0        │
│ LINEA_vacios          ┆ 0        │
│ MOLINETE_vacios       ┆ 0        │
│ ESTACION_vacios       ┆ 0        │
└───────────────────────┴──────────┘
--------------------------------------------------

=== REPORTE DE CALIDAD VIRTICAL: HISTORICO 2017 ===
shape: (18, 2)
┌───────────────────────┬──────────┐
│ Columna_Métrica       ┆ Cantidad │
│ ---                   ┆ ---      │
│ str                   ┆ u32      │
╞═══════════════════════╪══════════╡
│ V1_nulos              ┆ 0        │
│ FECHA_nulos           ┆ 0        │
│ DESDE_nulos           ┆ 0        │
│ HASTA_nulos           ┆ 0        │
│ LINEA_nulos           ┆ 0        │
│ MOLINETE_nulos        ┆ 0        │
│ ID_ESTACION_nulos     ┆ 0        │
│ ESTACION_nulos        ┆ 0        │
│ PAX_PAGOS_nulos       ┆ 0        │
│ PAX_PASES_PAGOS_nulos ┆ 0        │
│ PAX_FREQ_nulos        ┆ 0        │
│ TOTAL_nulos           ┆ 0        │
│ FECHA_vacios          ┆ 0        │
│ DESDE_vacios          ┆ 0        │
│ HASTA_vacios          ┆ 0        │
│ LINEA_vacios          ┆ 0        │
│ MOLINETE_vacios       ┆ 0        │
│ ESTACION_vacios       ┆ 0        │
└───────────────────────┴──────────┘
--------------------------------------------------

=== REPORTE DE CALIDAD VIRTICAL: HISTORICO 2018 ===
shape: (17, 2)
┌───────────────────────┬──────────┐
│ Columna_Métrica       ┆ Cantidad │
│ ---                   ┆ ---      │
│ str                   ┆ u32      │
╞═══════════════════════╪══════════╡
│ fecha_nulos           ┆ 78207    │
│ desde_nulos           ┆ 78207    │
│ hasta_nulos           ┆ 78207    │
│ linea_nulos           ┆ 78263    │
│ molinete_nulos        ┆ 78207    │
│ estacion_nulos        ┆ 78207    │
│ pax_pagos_nulos       ┆ 78207    │
│ pax_pases_pagos_nulos ┆ 78207    │
│ pax_franq_nulos       ┆ 78207    │
│ total_nulos           ┆ 78207    │
│ periodo_nulos         ┆ 0        │
│ fecha_vacios          ┆ 0        │
│ desde_vacios          ┆ 0        │
│ hasta_vacios          ┆ 0        │
│ linea_vacios          ┆ 0        │
│ molinete_vacios       ┆ 0        │
│ estacion_vacios       ┆ 0        │
└───────────────────────┴──────────┘
--------------------------------------------------

=== REPORTE DE CALIDAD VIRTICAL: HISTORICO 2019 ===
shape: (17, 2)
┌───────────────────────┬──────────┐
│ Columna_Métrica       ┆ Cantidad │
│ ---                   ┆ ---      │
│ str                   ┆ u32      │
╞═══════════════════════╪══════════╡
│ periodo_nulos         ┆ 0        │
│ fecha_nulos           ┆ 0        │
│ desde_nulos           ┆ 0        │
│ hasta_nulos           ┆ 0        │
│ linea_nulos           ┆ 0        │
│ molinete_nulos        ┆ 0        │
│ estacion_nulos        ┆ 0        │
│ pax_pagos_nulos       ┆ 0        │
│ pax_pases_pagos_nulos ┆ 0        │
│ pax_franq_nulos       ┆ 0        │
│ total_nulos           ┆ 0        │
│ fecha_vacios          ┆ 0        │
│ desde_vacios          ┆ 0        │
│ hasta_vacios          ┆ 0        │
│ linea_vacios          ┆ 0        │
│ molinete_vacios       ┆ 0        │
│ estacion_vacios       ┆ 0        │
└───────────────────────┴──────────┘
--------------------------------------------------

=== REPORTE DE CALIDAD VIRTICAL: HISTORICO 2020 ===
shape: (16, 2)
┌───────────────────────┬──────────┐
│ Columna_Métrica       ┆ Cantidad │
│ ---                   ┆ ---      │
│ str                   ┆ u32      │
╞═══════════════════════╪══════════╡
│ FECHA_nulos           ┆ 1836     │
│ DESDE_nulos           ┆ 1836     │
│ HASTA_nulos           ┆ 1836     │
│ LINEA_nulos           ┆ 1836     │
│ MOLINETE_nulos        ┆ 1836     │
│ ESTACION_nulos        ┆ 1836     │
│ pax_pagos_nulos       ┆ 1836     │
│ pax_pases_pagos_nulos ┆ 1836     │
│ pax_franq_nulos       ┆ 1836     │
│ pax_TOTAL_nulos       ┆ 1836     │
│ FECHA_vacios          ┆ 0        │
│ DESDE_vacios          ┆ 0        │
│ HASTA_vacios          ┆ 0        │
│ LINEA_vacios          ┆ 0        │
│ MOLINETE_vacios       ┆ 0        │
│ ESTACION_vacios       ┆ 0        │
└───────────────────────┴──────────┘
--------------------------------------------------

=== REPORTE DE CALIDAD VIRTICAL: HISTORICO 2021 ===
shape: (17, 2)
┌───────────────────────┬──────────┐
│ Columna_Métrica       ┆ Cantidad │
│ ---                   ┆ ---      │
│ str                   ┆ u32      │
╞═══════════════════════╪══════════╡
│ periodo_nulos         ┆ 0        │
│ FECHA_nulos           ┆ 0        │
│ DESDE_nulos           ┆ 0        │
│ HASTA_nulos           ┆ 0        │
│ LINEA_nulos           ┆ 0        │
│ MOLINETE_nulos        ┆ 0        │
│ ESTACION_nulos        ┆ 0        │
│ pax_pagos_nulos       ┆ 0        │
│ pax_pases_pagos_nulos ┆ 0        │
│ pax_franq_nulos       ┆ 0        │
│ pax_TOTAL_nulos       ┆ 0        │
│ FECHA_vacios          ┆ 0        │
│ DESDE_vacios          ┆ 0        │
│ HASTA_vacios          ┆ 0        │
│ LINEA_vacios          ┆ 0        │
│ MOLINETE_vacios       ┆ 0        │
│ ESTACION_vacios       ┆ 0        │
└───────────────────────┴──────────┘
--------------------------------------------------

In [ ]:
# Filtramos para ver qué tienen esas filas donde la fecha es nula
filas_rotas_2020 = historico_2020_df.filter(pl.col("FECHA").is_null())

# Mostramos las primeras 10 para chusmear qué estructura tienen
filas_rotas_2020.head(10)

shape: (10, 10)
┌───────┬───────┬───────┬───────┬──────────┬──────────┬───────────┬──────────┬──────────┬──────────┐
│ FECHA ┆ DESDE ┆ HASTA ┆ LINEA ┆ MOLINETE ┆ ESTACION ┆ pax_pagos ┆ pax_pase ┆ pax_fran ┆ pax_TOTA │
│ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---      ┆ ---      ┆ ---       ┆ s_pagos  ┆ q        ┆ L        │
│ str   ┆ str   ┆ str   ┆ str   ┆ str      ┆ str      ┆ i64       ┆ ---      ┆ ---      ┆ ---      │
│       ┆       ┆       ┆       ┆          ┆          ┆           ┆ i64      ┆ i64      ┆ i64      │
╞═══════╪═══════╪═══════╪═══════╪══════════╪══════════╪═══════════╪══════════╪══════════╪══════════╡
│ null  ┆ null  ┆ null  ┆ null  ┆ null     ┆ null     ┆ null      ┆ null     ┆ null     ┆ null     │
│ null  ┆ null  ┆ null  ┆ null  ┆ null     ┆ null     ┆ null      ┆ null     ┆ null     ┆ null     │
│ null  ┆ null  ┆ null  ┆ null  ┆ null     ┆ null     ┆ null      ┆ null     ┆ null     ┆ null     │
│ null  ┆ null  ┆ null  ┆ null  ┆ null     ┆ null     ┆ null      ┆ null     ┆ null     ┆ null     │
│ null  ┆ null  ┆ null  ┆ null  ┆ null     ┆ null     ┆ null      ┆ null     ┆ null     ┆ null     │
│ null  ┆ null  ┆ null  ┆ null  ┆ null     ┆ null     ┆ null      ┆ null     ┆ null     ┆ null     │
│ null  ┆ null  ┆ null  ┆ null  ┆ null     ┆ null     ┆ null      ┆ null     ┆ null     ┆ null     │
│ null  ┆ null  ┆ null  ┆ null  ┆ null     ┆ null     ┆ null      ┆ null     ┆ null     ┆ null     │
│ null  ┆ null  ┆ null  ┆ null  ┆ null     ┆ null     ┆ null      ┆ null     ┆ null     ┆ null     │
│ null  ┆ null  ┆ null  ┆ null  ┆ null     ┆ null     ┆ null      ┆ null     ┆ null     ┆ null     │
└───────┴───────┴───────┴───────┴──────────┴──────────┴───────────┴──────────┴──────────┴──────────┘

In [18]:
# Filtramos para ver qué tienen esas filas donde la fecha es nula
filas_rotas_2018 = historico_2018_df.filter(pl.col("fecha").is_null())

# Mostramos las primeras 10 para chusmear qué estructura tienen
print(filas_rotas_2018.head(10))

shape: (10, 11)
┌───────┬───────┬───────┬───────┬─────────┬─────────┬─────────┬─────────┬─────────┬───────┬────────┐
│ fecha ┆ desde ┆ hasta ┆ linea ┆ molinet ┆ estacio ┆ pax_pag ┆ pax_pas ┆ pax_fra ┆ total ┆ period │
│ ---   ┆ ---   ┆ ---   ┆ ---   ┆ e       ┆ n       ┆ os      ┆ es_pago ┆ nq      ┆ ---   ┆ o      │
│ str   ┆ str   ┆ str   ┆ str   ┆ ---     ┆ ---     ┆ ---     ┆ s       ┆ ---     ┆ f64   ┆ ---    │
│       ┆       ┆       ┆       ┆ str     ┆ str     ┆ f64     ┆ ---     ┆ f64     ┆       ┆ i64    │
│       ┆       ┆       ┆       ┆         ┆         ┆         ┆ f64     ┆         ┆       ┆        │
╞═══════╪═══════╪═══════╪═══════╪═════════╪═════════╪═════════╪═════════╪═════════╪═══════╪════════╡
│ null  ┆ null  ┆ null  ┆ null  ┆ null    ┆ null    ┆ null    ┆ null    ┆ null    ┆ null  ┆ 201807 │
│ null  ┆ null  ┆ null  ┆ null  ┆ null    ┆ null    ┆ null    ┆ null    ┆ null    ┆ null  ┆ 201807 │
│ null  ┆ null  ┆ null  ┆ null  ┆ null    ┆ null    ┆ null    ┆ null    ┆ null    ┆ null  ┆ 201807 │
│ null  ┆ null  ┆ null  ┆ null  ┆ null    ┆ null    ┆ null    ┆ null    ┆ null    ┆ null  ┆ 201807 │
│ null  ┆ null  ┆ null  ┆ null  ┆ null    ┆ null    ┆ null    ┆ null    ┆ null    ┆ null  ┆ 201807 │
│ null  ┆ null  ┆ null  ┆ null  ┆ null    ┆ null    ┆ null    ┆ null    ┆ null    ┆ null  ┆ 201807 │
│ null  ┆ null  ┆ null  ┆ null  ┆ null    ┆ null    ┆ null    ┆ null    ┆ null    ┆ null  ┆ 201807 │
│ null  ┆ null  ┆ null  ┆ null  ┆ null    ┆ null    ┆ null    ┆ null    ┆ null    ┆ null  ┆ 201807 │
│ null  ┆ null  ┆ null  ┆ null  ┆ null    ┆ null    ┆ null    ┆ null    ┆ null    ┆ null  ┆ 201807 │
│ null  ┆ null  ┆ null  ┆ null  ┆ null    ┆ null    ┆ null    ┆ null    ┆ null    ┆ null  ┆ 201807 │
└───────┴───────┴───────┴───────┴─────────┴─────────┴─────────┴─────────┴─────────┴───────┴────────┘

In [19]:
periodos_rotos = (
    historico_2018_df
    # 1. Filtramos las filas donde la fecha no tiene datos validos
    .filter((pl.col("fecha").str.strip_chars() == "") | (pl.col("fecha").is_null()))
    # 2. Nos quedamos solo con la columna periodo
    .select("periodo")
    # 3. Aplicamos el DISTINCT
    .unique()
    # 4. Lo ordenamos para que sea fácil de leer cronológicamente
    .sort("periodo")
)

print(periodos_rotos)

shape: (4, 1)
┌─────────┐
│ periodo │
│ ---     │
│ i64     │
╞═════════╡
│ 201807  │
│ 201809  │
│ 201810  │
│ 201811  │
└─────────┘

In [21]:

# Definimos la lista de períodos bajo la lupa que nos dio el DISTINCT
periodos_a_revisar = [201807, 201809, 201810, 201811]

# Configuramos Polars para que nos deje ver el mes completo (hasta 35 días por si las dudas)
with pl.Config(tbl_rows=35, fmt_str_lengths=50):
    
    for per in periodos_a_revisar:
        print(f"==================================================")
        print(f"🔍 AUDITORÍA CRONOLÓGICA DEL PERÍODO: {per}")
        print(f"==================================================")
        
        # 1. Filtramos y agrupamos por fecha para el período actual
        analisis_mes = (
            historico_2018_df
            .filter(
                (pl.col("periodo") == per) & 
                (pl.col("fecha").str.strip_chars() != "") & 
                (pl.col("fecha").is_not_null())
            )
            .group_by("fecha")
            .agg(pl.len().alias("registros_molinetes"))
            .sort("fecha")
        )
        
        # 2. Mostramos el desglose diario
        print(analisis_mes)
        
        # 3. Calculamos la cantidad de días únicos encontrados
        cant_dias = analisis_mes.height
        print(f"\n📊 Resultado para {per}: Se encontraron {cant_dias} días únicos con datos.")
        
        # Tiramos una alerta visual si el mes está incompleto
        if cant_dias < 30:
            print(f"⚠️ ¡ATENCIÓN! Al mes {per} le faltan días. Revisar bache de información.")
        else:
            print(f"✅ El mes {per} tiene el calendario completo.")
            
        print("-" * 50, "\n")

==================================================
🔍 AUDITORÍA CRONOLÓGICA DEL PERÍODO: 201807
==================================================
shape: (31, 2)
┌────────────┬─────────────────────┐
│ fecha      ┆ registros_molinetes │
│ ---        ┆ ---                 │
│ str        ┆ u32                 │
╞════════════╪═════════════════════╡
│ 2018-07-01 ┆ 24866               │
│ 2018-07-02 ┆ 36975               │
│ 2018-07-03 ┆ 37307               │
│ 2018-07-04 ┆ 37183               │
│ 2018-07-05 ┆ 37009               │
│ 2018-07-06 ┆ 37141               │
│ 2018-07-07 ┆ 31075               │
│ 2018-07-08 ┆ 24610               │
│ 2018-07-09 ┆ 24780               │
│ 2018-07-10 ┆ 36029               │
│ 2018-07-11 ┆ 36390               │
│ 2018-07-12 ┆ 36462               │
│ 2018-07-13 ┆ 36704               │
│ 2018-07-14 ┆ 32358               │
│ 2018-07-15 ┆ 25224               │
│ 2018-07-16 ┆ 35835               │
│ 2018-07-17 ┆ 36357               │
│ 2018-07-18 ┆ 36359               │
│ 2018-07-19 ┆ 34154               │
│ 2018-07-20 ┆ 35867               │
│ 2018-07-21 ┆ 31096               │
│ 2018-07-22 ┆ 24310               │
│ 2018-07-23 ┆ 34776               │
│ 2018-07-24 ┆ 35949               │
│ 2018-07-25 ┆ 35402               │
│ 2018-07-26 ┆ 35387               │
│ 2018-07-27 ┆ 35497               │
│ 2018-07-28 ┆ 32057               │
│ 2018-07-29 ┆ 25180               │
│ 2018-07-30 ┆ 35779               │
│ 2018-07-31 ┆ 33964               │
└────────────┴─────────────────────┘

📊 Resultado para 201807: Se encontraron 31 días únicos con datos.
✅ El mes 201807 tiene el calendario completo.
--------------------------------------------------

==================================================
🔍 AUDITORÍA CRONOLÓGICA DEL PERÍODO: 201809
==================================================
shape: (30, 2)
┌────────────┬─────────────────────┐
│ fecha      ┆ registros_molinetes │
│ ---        ┆ ---                 │
│ str        ┆ u32                 │
╞════════════╪═════════════════════╡
│ 2018-09-01 ┆ 31737               │
│ 2018-09-02 ┆ 25024               │
│ 2018-09-03 ┆ 36067               │
│ 2018-09-04 ┆ 35958               │
│ 2018-09-05 ┆ 35792               │
│ 2018-09-06 ┆ 36739               │
│ 2018-09-07 ┆ 37248               │
│ 2018-09-08 ┆ 32144               │
│ 2018-09-09 ┆ 24922               │
│ 2018-09-10 ┆ 36439               │
│ 2018-09-11 ┆ 35799               │
│ 2018-09-12 ┆ 36234               │
│ 2018-09-13 ┆ 36427               │
│ 2018-09-14 ┆ 36637               │
│ 2018-09-15 ┆ 31806               │
│ 2018-09-16 ┆ 24609               │
│ 2018-09-17 ┆ 36386               │
│ 2018-09-18 ┆ 36598               │
│ 2018-09-19 ┆ 36360               │
│ 2018-09-20 ┆ 36503               │
│ 2018-09-21 ┆ 36607               │
│ 2018-09-22 ┆ 31681               │
│ 2018-09-23 ┆ 24757               │
│ 2018-09-24 ┆ 29988               │
│ 2018-09-25 ┆ 130                 │
│ 2018-09-26 ┆ 36352               │
│ 2018-09-27 ┆ 36184               │
│ 2018-09-28 ┆ 36361               │
│ 2018-09-29 ┆ 29587               │
│ 2018-09-30 ┆ 24730               │
└────────────┴─────────────────────┘

📊 Resultado para 201809: Se encontraron 30 días únicos con datos.
✅ El mes 201809 tiene el calendario completo.
--------------------------------------------------

==================================================
🔍 AUDITORÍA CRONOLÓGICA DEL PERÍODO: 201810
==================================================
shape: (31, 2)
┌────────────┬─────────────────────┐
│ fecha      ┆ registros_molinetes │
│ ---        ┆ ---                 │
│ str        ┆ u32                 │
╞════════════╪═════════════════════╡
│ 2018-10-01 ┆ 35895               │
│ 2018-10-02 ┆ 36736               │
│ 2018-10-03 ┆ 36757               │
│ 2018-10-04 ┆ 36846               │
│ 2018-10-05 ┆ 37222               │
│ 2018-10-06 ┆ 32639               │
│ 2018-10-07 ┆ 26359               │
│ 2018-10-08 ┆ 37071               │
│ 2018-10-09 ┆ 37280               │
│ 2018-10-10 ┆ 37115               │
│ 2018-10-11 ┆ 37382               │
│ 2018-10-12 ┆ 37395               │
│ 2018-10-13 ┆ 32270               │
│ 2018-10-14 ┆ 26221               │
│ 2018-10-15 ┆ 26025               │
│ 2018-10-16 ┆ 37097               │
│ 2018-10-17 ┆ 37516               │
│ 2018-10-18 ┆ 37596               │
│ 2018-10-19 ┆ 37275               │
│ 2018-10-20 ┆ 32559               │
│ 2018-10-21 ┆ 25894               │
│ 2018-10-22 ┆ 36982               │
│ 2018-10-23 ┆ 37341               │
│ 2018-10-24 ┆ 36686               │
│ 2018-10-25 ┆ 37057               │
│ 2018-10-26 ┆ 37384               │
│ 2018-10-27 ┆ 32968               │
│ 2018-10-28 ┆ 26509               │
│ 2018-10-29 ┆ 36946               │
│ 2018-10-30 ┆ 36893               │
│ 2018-10-31 ┆ 8342                │
└────────────┴─────────────────────┘

📊 Resultado para 201810: Se encontraron 31 días únicos con datos.
✅ El mes 201810 tiene el calendario completo.
--------------------------------------------------

==================================================
🔍 AUDITORÍA CRONOLÓGICA DEL PERÍODO: 201811
==================================================
shape: (30, 2)
┌────────────┬─────────────────────┐
│ fecha      ┆ registros_molinetes │
│ ---        ┆ ---                 │
│ str        ┆ u32                 │
╞════════════╪═════════════════════╡
│ 2018-11-01 ┆ 37279               │
│ 2018-11-02 ┆ 37455               │
│ 2018-11-03 ┆ 33127               │
│ 2018-11-04 ┆ 26458               │
│ 2018-11-05 ┆ 37374               │
│ 2018-11-06 ┆ 37384               │
│ 2018-11-07 ┆ 37607               │
│ 2018-11-08 ┆ 37776               │
│ 2018-11-09 ┆ 37772               │
│ 2018-11-10 ┆ 26203               │
│ 2018-11-11 ┆ 24335               │
│ 2018-11-12 ┆ 37102               │
│ 2018-11-13 ┆ 37298               │
│ 2018-11-14 ┆ 37182               │
│ 2018-11-15 ┆ 36011               │
│ 2018-11-16 ┆ 37764               │
│ 2018-11-17 ┆ 33009               │
│ 2018-11-18 ┆ 26798               │
│ 2018-11-19 ┆ 26623               │
│ 2018-11-20 ┆ 37695               │
│ 2018-11-21 ┆ 37759               │
│ 2018-11-22 ┆ 37662               │
│ 2018-11-23 ┆ 37766               │
│ 2018-11-24 ┆ 30378               │
│ 2018-11-25 ┆ 26017               │
│ 2018-11-26 ┆ 37902               │
│ 2018-11-27 ┆ 34473               │
│ 2018-11-28 ┆ 38178               │
│ 2018-11-29 ┆ 35777               │
│ 2018-11-30 ┆ 117                 │
└────────────┴─────────────────────┘

📊 Resultado para 201811: Se encontraron 30 días únicos con datos.
✅ El mes 201811 tiene el calendario completo.
--------------------------------------------------

In [22]:

# Definimos los 4 períodos rancio que estamos auditando
periodos_a_revisar = [201807, 201809, 201810, 201811]

# Filtramos el dataset quedándonos SOLO con los datos válidos de esos meses
df_validos_2018 = historico_2018_df.filter(
    (pl.col("periodo").is_in(periodos_a_revisar)) &
    (pl.col("fecha").str.strip_chars() != "") &
    (pl.col("fecha").is_not_null())
)

print("==================================================")
# 1. Chequeo de Líneas
lineas_unicas = df_validos_2018.select("linea").unique().sort("linea")
print(f"📊 LÍNEAS PRESENTES ({lineas_unicas.height}):")
print(lineas_unicas.to_series().to_list()) # Lo mostramos como lista para leerlo rápido

print("-" * 50)
# 2. Chequeo de Cantidad de Estaciones por Línea (más sutil que un unique global)
estaciones_por_linea = (
    df_validos_2018
    .group_by("linea")
    .agg(pl.col("estacion").n_unique().alias("cant_estaciones"))
    .sort("linea")
)
print("📊 CANTIDAD DE ESTACIONES ÚNICAS POR LÍNEA:")
print(estaciones_por_linea)

print("-" * 50)
# 3. Chequeo de Franjas Horarias (desde/hasta)
# Contamos cuántas combinaciones únicas de franjas de 15 min tenemos
franjas_horarias = df_validos_2018.select(["desde", "hasta"]).unique()
print(f"📊 CANTIDAD DE FRANJAS HORARIAS DE 15 MIN ENCONTRADAS: {franjas_horarias.height}")
print("El esquema de subte suele tener entre 70 y 90 franjas según apertura/cierre.")
print("==================================================")

==================================================
📊 LÍNEAS PRESENTES (6):
['LineaA', 'LineaB', 'LineaC', 'LineaD', 'LineaE', 'LineaH']
--------------------------------------------------
📊 CANTIDAD DE ESTACIONES ÚNICAS POR LÍNEA:
shape: (6, 2)
┌────────┬─────────────────┐
│ linea  ┆ cant_estaciones │
│ ---    ┆ ---             │
│ str    ┆ u32             │
╞════════╪═════════════════╡
│ LineaA ┆ 18              │
│ LineaB ┆ 17              │
│ LineaC ┆ 9               │
│ LineaD ┆ 16              │
│ LineaE ┆ 15              │
│ LineaH ┆ 12              │
└────────┴─────────────────┘
--------------------------------------------------
📊 CANTIDAD DE FRANJAS HORARIAS DE 15 MIN ENCONTRADAS: 96
El esquema de subte suele tener entre 70 y 90 franjas según apertura/cierre.
==================================================

### Conclusión de nulos

Se revisaron los nulos de los dataframes que los presentaban de forma consistente (en todos los campos)

En el caso del 2020 toda la fila estaba nula, por lo que se deduce que el registro era nulo.

En el caso del 2018 los nulos presentaban registro en el campo "Período", por lo que hubo que hacer un análisis más profundo para revisar si incluso sin esos datos el resto del dataset cuadraba.

### Duplicados

In [23]:
for anio in range(2014, 2022):
    nombre_var = f"historico_{anio}_df"
    
    if nombre_var in globals():
        df_actual = globals()[nombre_var]
        
        # 1. Duplicados Exactos: Filas que son un calco absoluto en TODAS sus columnas
        total_filas = df_actual.height
        filas_unicas_absolutas = df_actual.unique().height
        duplicados_exactos = total_filas - filas_unicas_absolutas
        
        # 2. Identificar dinámicamente las columnas clave de este año en particular
        # Buscamos cómo se escriben 'fecha', 'desde', 'hasta', 'linea', 'molinete', 'estacion' sin importar mayúsculas/minúsculas
        columnas_actuales = df_actual.columns
        columnas_clave = [
            col for col in columnas_actuales 
            if col.upper() in ["FECHA", "DESDE", "HASTA", "LINEA", "MOLINETE", "ESTACION"]
        ]
        
        # 3. Duplicados por Clave: Mismo momento, mismo molinete, misma estación
        # (Aunque difieran en la columna de pasajeros por algún error de carga)
        filas_unicas_clave = df_actual.unique(subset=columnas_clave).height
        duplicados_clave = total_filas - filas_unicas_clave
        
        # Imprimimos el reporte formal para el informe de la materia
        print(f"=== REPORTE DE DUPLICADOS: HISTORICO {anio} ===")
        print(f"• Total de registros evaluados: {total_filas:,}")
        print(f"• Filas idénticas (100% duplicadas): {duplicados_exactos:,}")
        print(f"• Duplicados por clave espacio-temporal: {duplicados_clave:,}")
        
        if duplicados_exactos == 0 and duplicados_clave == 0:
            print("✅ Conclusión: El dataset no presenta anomalías de duplicación en esta etapa.")
        else:
            print("⚠️ Conclusión: Se detectaron registros duplicados a tratar en la fase de corrección.")
            
        print("-" * 60, "\n")

=== REPORTE DE DUPLICADOS: HISTORICO 2014 ===
• Total de registros evaluados: 10,857,244
• Filas idénticas (100% duplicadas): 0
• Duplicados por clave espacio-temporal: 0
✅ Conclusión: El dataset no presenta anomalías de duplicación en esta etapa.
------------------------------------------------------------

=== REPORTE DE DUPLICADOS: HISTORICO 2015 ===
• Total de registros evaluados: 10,958,582
• Filas idénticas (100% duplicadas): 0
• Duplicados por clave espacio-temporal: 0
✅ Conclusión: El dataset no presenta anomalías de duplicación en esta etapa.
------------------------------------------------------------

=== REPORTE DE DUPLICADOS: HISTORICO 2016 ===
• Total de registros evaluados: 11,542,322
• Filas idénticas (100% duplicadas): 0
• Duplicados por clave espacio-temporal: 0
✅ Conclusión: El dataset no presenta anomalías de duplicación en esta etapa.
------------------------------------------------------------

=== REPORTE DE DUPLICADOS: HISTORICO 2017 ===
• Total de registros evaluados: 11,938,476
• Filas idénticas (100% duplicadas): 0
• Duplicados por clave espacio-temporal: 0
✅ Conclusión: El dataset no presenta anomalías de duplicación en esta etapa.
------------------------------------------------------------

=== REPORTE DE DUPLICADOS: HISTORICO 2018 ===
• Total de registros evaluados: 12,136,454
• Filas idénticas (100% duplicadas): 78,203
• Duplicados por clave espacio-temporal: 78,206
⚠️ Conclusión: Se detectaron registros duplicados a tratar en la fase de corrección.
------------------------------------------------------------

=== REPORTE DE DUPLICADOS: HISTORICO 2019 ===
• Total de registros evaluados: 12,662,343
• Filas idénticas (100% duplicadas): 0
• Duplicados por clave espacio-temporal: 0
✅ Conclusión: El dataset no presenta anomalías de duplicación en esta etapa.
------------------------------------------------------------

=== REPORTE DE DUPLICADOS: HISTORICO 2020 ===
• Total de registros evaluados: 5,781,006
• Filas idénticas (100% duplicadas): 9,782
• Duplicados por clave espacio-temporal: 108,656
⚠️ Conclusión: Se detectaron registros duplicados a tratar en la fase de corrección.
------------------------------------------------------------

=== REPORTE DE DUPLICADOS: HISTORICO 2021 ===
• Total de registros evaluados: 8,071,680
• Filas idénticas (100% duplicadas): 0
• Duplicados por clave espacio-temporal: 0
✅ Conclusión: El dataset no presenta anomalías de duplicación en esta etapa.
------------------------------------------------------------

En el reporte de 2018 la cantida de duplicados coincide con la cantidad de nulos. Se inicia análisis exploratorio de esa cuestión.

In [24]:
# 1. Identificamos las columnas clave del 2018 (en minúsculas)
columnas_clave_2018 = ["fecha", "desde", "hasta", "linea", "molinete", "estacion"]

# 2. Filtramos el dataframe:
#    - Primero sacamos las filas fantasmas (las que tienen fecha vacía o nula)
#    - De lo que queda, filtramos para ver SOLO las filas que están duplicadas por clave
duplicados_reales_2018 = (
    historico_2018_df
    .filter(
        (pl.col("fecha").str.strip_chars() != "") & 
        (pl.col("fecha").is_not_null())
    )
    .filter(
        pl.struct(columnas_clave_2018).is_duplicated()
    )
    .sort(columnas_clave_2018)
)

print("=== DUPLICADOS REALES DETECTADOS EN 2018 ===")
print(duplicados_reales_2018)

=== DUPLICADOS REALES DETECTADOS EN 2018 ===
shape: (0, 11)
┌───────┬───────┬───────┬───────┬─────────┬─────────┬─────────┬─────────┬─────────┬───────┬────────┐
│ fecha ┆ desde ┆ hasta ┆ linea ┆ molinet ┆ estacio ┆ pax_pag ┆ pax_pas ┆ pax_fra ┆ total ┆ period │
│ ---   ┆ ---   ┆ ---   ┆ ---   ┆ e       ┆ n       ┆ os      ┆ es_pago ┆ nq      ┆ ---   ┆ o      │
│ str   ┆ str   ┆ str   ┆ str   ┆ ---     ┆ ---     ┆ ---     ┆ s       ┆ ---     ┆ f64   ┆ ---    │
│       ┆       ┆       ┆       ┆ str     ┆ str     ┆ f64     ┆ ---     ┆ f64     ┆       ┆ i64    │
│       ┆       ┆       ┆       ┆         ┆         ┆         ┆ f64     ┆         ┆       ┆        │
╞═══════╪═══════╪═══════╪═══════╪═════════╪═════════╪═════════╪═════════╪═════════╪═══════╪════════╡
└───────┴───────┴───────┴───────┴─────────┴─────────┴─────────┴─────────┴─────────┴───────┴────────┘

### Outliers

In [ ]:
print("==================================================================")
print("🔍 AUDITORÍA DE OUTLIERS NUMÉRICOS: PASAJEROS TOTALES")
print("==================================================================")

for anio in range(2014, 2022):
    nombre_var = f"historico_{anio}_df"
    
    if nombre_var in globals():
        df_actual = globals()[nombre_var]
        
        # Identificamos la columna del total de pasajeros de forma dinámica
        col_total = [c for c in df_actual.columns if "TOTAL" in c.upper()][0]
        
        # Calculamos estadísticas clave sobre esa columna
        stats = df_actual.select([
            pl.col(col_total).min().alias("minimo"),
            pl.col(col_total).max().alias("maximo"),
            pl.col(col_total).mean().alias("media"),
            pl.col(col_total).std().alias("desvio_estandar"),
            # Contamos si hay algún negativo colgado
            (pl.col(col_total) < 0).sum().alias("cant_negativos")
        ])
        
        print(f"📈 HISTÓRICO {anio} (Columna: '{col_total}'):")
        print(f"  • Valor Mínimo: {stats['minimo'][0]}")
        print(f"  • Valor Máximo: {stats['maximo'][0]:,}")
        print(f"  • Media / Promedio: {stats['media'][0]:.2f}")
        print(f"  • Desvío Estándar: {stats['desvio_estandar'][0]:.2f}")
        print(f"  • Registros Negativos: {stats['cant_negativos'][0]}")
        
        # Alerta metodológica si el máximo es absurdamente gigante para 15 minutos
        if stats['maximo'][0] > 15000:
            print(f"  ⚠️ ALERTA: El valor máximo parece físicamente imposible para un molinete en 15 min.")
        if stats['cant_negativos'][0] > 0:
            print(f"  ⚠️ ALERTA: Hay valores negativos que romperían el modelo.")
            
        print("-" * 66)

==================================================================
🔍 AUDITORÍA DE OUTLIERS NUMÉRICOS: PASAJEROS TOTALES
==================================================================
📈 HISTÓRICO 2014 (Columna: 'PAX_TOTAL'):
  • Valor Mínimo: 0
  • Valor Máximo: 14,538
  • Media / Promedio: 23.50
  • Desvío Estándar: 27.73
  • Registros Negativos Raros: 0
------------------------------------------------------------------
📈 HISTÓRICO 2015 (Columna: 'total'):
  • Valor Mínimo: 0.0
  • Valor Máximo: 423.0
  • Media / Promedio: 25.78
  • Desvío Estándar: 28.99
  • Registros Negativos Raros: 0
------------------------------------------------------------------
📈 HISTÓRICO 2016 (Columna: 'TOTAL'):
  • Valor Mínimo: 0
  • Valor Máximo: 362
  • Media / Promedio: 27.24
  • Desvío Estándar: 30.05
  • Registros Negativos Raros: 0
------------------------------------------------------------------
📈 HISTÓRICO 2017 (Columna: 'TOTAL'):
  • Valor Mínimo: 0
  • Valor Máximo: 399
  • Media / Promedio: 27.53
  • Desvío Estándar: 30.12
  • Registros Negativos Raros: 0
------------------------------------------------------------------
📈 HISTÓRICO 2018 (Columna: 'total'):
  • Valor Mínimo: 0.0
  • Valor Máximo: 464.0
  • Media / Promedio: 28.89
  • Desvío Estándar: 30.89
  • Registros Negativos Raros: 0
------------------------------------------------------------------
📈 HISTÓRICO 2019 (Columna: 'total'):
  • Valor Mínimo: 0.0
  • Valor Máximo: 12,459.0
  • Media / Promedio: 26.96
  • Desvío Estándar: 29.40
  • Registros Negativos Raros: 0
------------------------------------------------------------------
📈 HISTÓRICO 2020 (Columna: 'pax_TOTAL'):
  • Valor Mínimo: 1
  • Valor Máximo: 310
  • Media / Promedio: 13.41
  • Desvío Estándar: 19.66
  • Registros Negativos Raros: 0
------------------------------------------------------------------
📈 HISTÓRICO 2021 (Columna: 'pax_TOTAL'):
  • Valor Mínimo: 1
  • Valor Máximo: 298
  • Media / Promedio: 11.90
  • Desvío Estándar: 14.92
  • Registros Negativos Raros: 0
------------------------------------------------------------------

In [26]:
print("==================================================================")
print("🔍 AUDITORÍA DE OUTLIERS TEMPORALES (FECHAS Y FRANJAS)")
print("==================================================================")

for anio in range(2014, 2022):
    nombre_var = f"historico_{anio}_df"
    
    if nombre_var in globals():
        df_actual = globals()[nombre_var]
        
        # Mapeamos dinámicamente las columnas temporales ignorando case-sensitive
        col_fecha = [c for c in df_actual.columns if c.upper() == "FECHA"][0]
        col_desde = [c for c in df_actual.columns if c.upper() == "DESDE"][0]
        col_hasta = [c for c in df_actual.columns if c.upper() == "HASTA"][0]
        
        # Filtramos primero las filas vacías que ya sabemos que existen para no alterar el análisis
        df_limpio_temp = df_actual.filter(
            (pl.col(col_fecha).str.strip_chars() != "") & (pl.col(col_fecha).is_not_null())
        )
        
        # 1. Buscamos si hay fechas que no pertenecen a ese año (outliers cronológicos)
        # Extraemos los primeros 4 caracteres de la fecha (asumiendo formato YYYY-MM-DD o YYYY/MM/DD)
        fechas_fuera_de_anio = df_limpio_temp.filter(
            ~pl.col(col_fecha).str.slice(0, 4).str.contains(str(anio))
        )
        
        # 2. Validamos que la longitud del texto de las horas sea el correcto (ej: "08:00:00" o "08:00")
        # Si un campo tiene un formato deformado (ej: "25:99"), salta acá
        horas_desde_raras = df_limpio_temp.filter(
            pl.col(col_desde).str.len_chars() > 8
        )
        
        print(f"📅 TEMPORAL {anio}:")
        print(f"  • Registros con fechas que NO corresponden al año {anio}: {fechas_fuera_de_anio.height}")
        print(f"  • Registros con formatos de hora sospechosos/largos: {horas_desde_raras.height}")
        
        if fechas_fuera_de_anio.height > 0:
            print(f"  ⚠️ ALERTA: Hay fechas mezcladas de otros años en este archivo.")
            # Te muestra una muestra de qué años se colaron
            print("    Años detectados:", fechas_fuera_de_anio.select(pl.col(col_fecha).str.slice(0, 4)).unique().to_series().to_list())
            
        print("-" * 66)

==================================================================
🔍 AUDITORÍA DE OUTLIERS TEMPORALES (FECHAS Y FRANJAS)
==================================================================
📅 TEMPORAL 2014:
  • Registros con fechas que NO corresponden al año 2014: 0
  • Registros con formatos de hora sospechosos/largos: 0
------------------------------------------------------------------
📅 TEMPORAL 2015:
  • Registros con fechas que NO corresponden al año 2015: 0
  • Registros con formatos de hora sospechosos/largos: 0
------------------------------------------------------------------
📅 TEMPORAL 2016:
  • Registros con fechas que NO corresponden al año 2016: 11542322
  • Registros con formatos de hora sospechosos/largos: 0
  ⚠️ ALERTA: Hay fechas mezcladas de otros años en este archivo.
    Años detectados: ['13/1', '23/1', '04/1', '29/0', '30/1', '22/1', '09/0', '28/1', '17/1', '02/0', '22/0', '31/1', '03/0', '25/0', '01/1', '15/0', '20/0', '15/1', '31/0', '27/0', '12/0', '08/1', '01/0', '04/0', '11/1', '26/1', '21/0', '08/0', '10/1', '17/0', '18/0', '26/0', '18/1', '07/0', '24/0', '27/1', '25/1', '20/1', '02/1', '30/0', '19/1', '14/1', '07/1', '03/1', '11/0', '13/0', '05/1', '16/1', '28/0', '10/0', '09/1', '29/1', '23/0', '24/1', '16/0', '06/0', '06/1', '12/1', '14/0', '05/0', '19/0', '21/1']
------------------------------------------------------------------
📅 TEMPORAL 2017:
  • Registros con fechas que NO corresponden al año 2017: 11938476
  • Registros con formatos de hora sospechosos/largos: 0
  ⚠️ ALERTA: Hay fechas mezcladas de otros años en este archivo.
    Años detectados: ['23/0', '04/0', '14/1', '03/0', '18/0', '30/0', '31/1', '11/0', '06/1', '05/0', '28/1', '20/1', '13/1', '08/0', '20/0', '18/1', '10/1', '23/1', '30/1', '01/0', '03/1', '25/0', '15/1', '24/1', '12/0', '09/1', '05/1', '29/0', '01/1', '24/0', '27/1', '19/0', '26/0', '07/0', '22/0', '22/1', '25/1', '21/0', '26/1', '12/1', '09/0', '19/1', '02/1', '13/0', '27/0', '17/0', '17/1', '14/0', '08/1', '15/0', '10/0', '16/0', '21/1', '31/0', '06/0', '28/0', '04/1', '07/1', '11/1', '16/1', '29/1', '02/0']
------------------------------------------------------------------
📅 TEMPORAL 2018:
  • Registros con fechas que NO corresponden al año 2018: 0
  • Registros con formatos de hora sospechosos/largos: 0
------------------------------------------------------------------
📅 TEMPORAL 2019:
  • Registros con fechas que NO corresponden al año 2019: 0
  • Registros con formatos de hora sospechosos/largos: 0
------------------------------------------------------------------
📅 TEMPORAL 2020:
  • Registros con fechas que NO corresponden al año 2020: 5779170
  • Registros con formatos de hora sospechosos/largos: 0
  ⚠️ ALERTA: Hay fechas mezcladas de otros años en este archivo.
    Años detectados: ['14/0', '8/30', '4/12', '8/7/', '07/0', '1/12', '4/11', '23/0', '3/12', '3/25', '6/20', '4/18', '28/1', '10/3', '9/22', '5/13', '5/6/', '9/7/', '5/8/', '8/17', '8/23', '7/25', '06/0', '24/0', '6/18', '3/3/', '17/1', '19/1', '5/30', '05/0', '3/26', '17/0', '4/28', '6/25', '10/2', '7/21', '6/3/', '6/10', '9/28', '8/29', '10/4', '5/5/', '4/16', '5/23', '6/7/', '3/10', '7/11', '3/2/', '8/25', '4/23', '4/24', '02/0', '12/1', '6/17', '03/0', '6/11', '4/13', '4/30', '3/22', '3/31', '4/10', '7/14', '9/23', '22/1', '8/1/', '4/29', '3/1/', '5/22', '3/15', '9/15', '7/5/', '3/28', '25/0', '8/15', '8/6/', '31/1', '3/16', '13/0', '4/4/', '8/2/', '7/23', '26/1', '2/11', '31/0', '9/16', '10/7', '19/0', '4/15', '04/0', '5/24', '9/19', '7/4/', '10/1', '7/2/', '9/26', '7/19', '25/1', '15/0', '5/27', '7/27', '16/0', '6/9/', '7/22', '7/6/', '6/26', '9/30', '7/9/', '21/0', '9/3/', '18/1', '5/20', '7/16', '7/10', '01/0', '4/6/', '3/18', '9/5/', '9/8/', '8/18', '5/31', '3/23', '11/1', '6/5/', '7/30', '14/1', '9/18', '3/8/', '3/17', '8/28', '5/25', '9/17', '6/4/', '23/1', '7/26', '6/28', '24/1', '28/0', '6/29', '6/15', '8/13', '7/29', '1/11', '5/19', '10/6', '6/12', '7/3/', '7/17', '7/20', '4/21', '9/2/', '4/20', '6/22', '9/4/', '29/1', '9/6/', '27/1', '11/0', '21/1', '6/8/', '5/15', '9/9/', '6/1/', '8/21', '9/12', '9/21', '2/12', '5/4/', '3/20', '8/11', '6/27', '5/17', '3/7/', '4/19', '8/31', '3/24', '6/14', '3/29', '4/1/', '3/21', '8/19', '8/8/', '30/0', '8/27', '27/0', '10/5', '7/18', '7/13', '5/28', '10/9', '12/0', '7/7/', '8/14', '7/28', '7/12', '3/19', '6/24', '3/30', '3/4/', '9/14', '5/18', '9/13', '3/6/', '9/24', '9/1/', '4/2/', '6/19', '7/24', '4/14', '4/5/', '15/1', '6/23', '5/26', '5/29', '9/29', '3/11', '4/9/', '8/20', '6/21', '4/26', '10/8', '8/24', '7/31', '3/13', '8/4/', '16/1', '9/20', '7/1/', '5/16', '6/16', '3/5/', '5/3/', '5/9/', '5/7/', '08/0', '09/0', '5/21', '3/27', '26/0', '22/0', '3/14', '8/12', '8/3/', '9/11', '5/14', '7/15', '9/25', '18/0', '5/11', '4/17', '5/1/', '30/1', '5/2/', '8/22', '4/27', '5/12', '3/9/', '7/8/', '8/10', '6/6/', '6/30', '5/10', '10/0', '20/0', '8/5/', '20/1', '29/0', '9/10', '4/22', '8/26', '8/9/', '4/25', '8/16', '6/13', '4/3/', '9/27', '4/8/', '13/1', '4/7/', '6/2/']
------------------------------------------------------------------
📅 TEMPORAL 2021:
  • Registros con fechas que NO corresponden al año 2021: 7028067
  • Registros con formatos de hora sospechosos/largos: 0
  ⚠️ ALERTA: Hay fechas mezcladas de otros años en este archivo.
    Años detectados: ['16/6', '2/4/', '2/6/', '1/11', '30/4', '24/9', '7/9/', '14/5', '31/5', '7/6/', '5/12', '22/8', '16/8', '6/1/', '3/7/', '10/5', '14/1', '25/7', '15/1', '7/1/', '28/9', '20/7', '25/9', '27/1', '29/8', '5/11', '4/7/', '24/8', '2/8/', '25/8', '28/8', '9/11', '9/4/', '3/12', '27/7', '30/5', '1/10', '19/4', '27/8', '1/12', '23/5', '11/5', '10/7', '8/1/', '29/5', '5/8/', '6/9/', '16/4', '15/6', '19/7', '3/6/', '31/1', '23/6', '28/5', '26/5', '22/7', '17/4', '4/4/', '12/1', '12/6', '4/1/', '8/12', '22/1', '30/7', '17/8', '18/5', '19/5', '18/8', '5/1/', '26/4', '21/4', '22/6', '12/9', '24/4', '13/5', '27/6', '6/8/', '18/1', '17/7', '9/12', '10/6', '28/4', '29/1', '19/9', '13/9', '15/7', '2/1/', '5/4/', '18/7', '3/11', '5/6/', '3/8/', '11/6', '25/1', '16/1', '30/6', '2/7/', '23/8', '13/8', '9/9/', '30/8', '9/5/', '30/9', '1/1/', '9/10', '9/6/', '28/7', '21/8', '11/1', '8/7/', '29/9', '3/5/', '21/5', '11/8', '18/6', '18/4', '5/9/', '16/9', '23/1', '6/10', '14/6', '9/1/', '7/5/', '2/9/', '17/6', '14/9', '26/8', '29/4', '1/5/', '25/6', '4/12', '10/4', '29/6', '20/8', '13/4', '6/4/', '21/1', '2/12', '22/5', '16/7', '14/4', '3/9/', '20/4', '13/7', '12/7', '1/9/', '2/11', '3/4/', '30/1', '12/4', '17/9', '12/8', '27/4', '7/11', '10/9', '31/8', '23/4', '27/5', '23/7', '4/10', '25/4', '28/1', '6/7/', '6/12', '16/5', '3/10', '1/8/', '4/8/', '13/1', '15/9', '17/1', '26/6', '5/10', '3/1/', '7/8/', '1/7/', '22/9', '20/9', '4/11', '10/1', '8/10', '15/8', '6/5/', '19/8', '8/6/', '11/7', '13/6', '8/11', '5/5/', '26/7', '26/9', '4/9/', '31/7', '5/7/', '7/10', '24/5', '20/5', '8/4/', '18/9', '22/4', '17/5', '19/6', '4/6/', '26/1', '9/7/', '10/8', '7/4/', '25/5', '7/12', '9/8/', '11/4', '24/7', '15/4', '11/9', '12/5', '8/9/', '8/5/', '6/11', '7/7/', '1/6/', '21/6', '20/6', '4/5/', '28/6', '20/1', '14/8', '6/6/', '15/5', '21/7', '2/10', '27/9', '24/1', '21/9', '8/8/', '1/4/', '24/6', '2/5/', '19/1', '14/7', '29/7', '23/9']
------------------------------------------------------------------

In [27]:
for anio in [2016, 2017, 2020, 2021]:
    nombre_var = f"historico_{anio}_df"
    
    if nombre_var in globals():
        df_actual = globals()[nombre_var]
        col_fecha = [c for c in df_actual.columns if c.upper() == "FECHA"][0]
        
        # Filtramos las que no tengan nulos ni vacíos
        df_limpio = df_actual.filter(
            (pl.col(col_fecha).str.strip_chars() != "") & (pl.col(col_fecha).is_not_null())
        )
        
        # Tomamos una muestra de las primeras 3 fechas reales para ver el orden (D/M/A o A/M/D)
        muestra_fechas = df_limpio.select(col_fecha).head(3).to_series().to_list()
        
        print(f"📅 DIAGNÓSTICO DE FORMATO - AÑO {anio}:")
        print(f"  • Estructura visual de las fechas (Muestra): {muestra_fechas}")
        print("-" * 60)

📅 DIAGNÓSTICO DE FORMATO - AÑO 2016:
  • Estructura visual de las fechas (Muestra): ['02/01/2016', '02/01/2016', '05/01/2016']
------------------------------------------------------------
📅 DIAGNÓSTICO DE FORMATO - AÑO 2017:
  • Estructura visual de las fechas (Muestra): ['01/01/2017', '01/01/2017', '01/01/2017']
------------------------------------------------------------
📅 DIAGNÓSTICO DE FORMATO - AÑO 2020:
  • Estructura visual de las fechas (Muestra): ['01/01/2020', '01/01/2020', '01/01/2020']
------------------------------------------------------------
📅 DIAGNÓSTICO DE FORMATO - AÑO 2021:
  • Estructura visual de las fechas (Muestra): ['1/1/2021', '1/1/2021', '1/1/2021']
------------------------------------------------------------

https://github.com/AleLoredo/UGR-metodologia/blob/eze/UGR_Metodologia_TP1_subte.ipynb