In [ ]:
!pip install -U polars pyarrow

Requirement already satisfied: polars in /usr/local/lib/python3.12/dist-packages (1.35.2)
Collecting polars
  Downloading polars-1.41.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)
Collecting pyarrow
  Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting polars-runtime-32==1.41.2 (from polars)
  Downloading polars_runtime_32-1.41.2-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Downloading polars-1.41.2-py3-none-any.whl (833 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 833.4/833.4 kB 6.7 MB/s eta 0:00:00
Downloading polars_runtime_32-1.41.2-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (56.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.4/56.4 MB 16.4 MB/s eta 0:00:00
Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (48.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 10.9 MB/s eta 0:00:00
Installing collected packages: pyarrow, polars-runtime-32, polars
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: polars-runtime-32
    Found existing installation: polars-runtime-32 1.35.2
    Uninstalling polars-runtime-32-1.35.2:
      Successfully uninstalled polars-runtime-32-1.35.2
  Attempting uninstall: polars
    Found existing installation: polars 1.35.2
    Uninstalling polars-1.35.2:
      Successfully uninstalled polars-1.35.2
Successfully installed polars-1.41.2 polars-runtime-32-1.41.2 pyarrow-24.0.0

In [ ]:
import zipfile
import os
import polars as pl
import glob

In [ ]:
'''
!mkdir -p downloads

!wget -O /content/downloads/molinetes_2022.zip "https://data.buenosaires.gob.ar/dataset/subte-viajes-molinetes/resource/51f7cdcf-04dd-40c0-b0b1-32b016d3ab6b/download"

!wget -O /content/downloads/molinetes_2023.zip "https://data.buenosaires.gob.ar/dataset/subte-viajes-molinetes/resource/8d752670-38d0-49f6-b6df-0d9948c5e993/download"

!wget -O /content/downloads/molinetes_2024.zip "https://data.buenosaires.gob.ar/dataset/subte-viajes-molinetes/resource/9faf4137-63c9-4f15-848c-248c166b54ea/download"

!wget -O /content/downloads/molinetes_2025.zip "https://data.buenosaires.gob.ar/dataset/subte-viajes-molinetes/resource/0d689701-9efd-4644-85d0-f6a1504509f1/download"
'''

--2026-06-05 03:09:29--  https://data.buenosaires.gob.ar/dataset/subte-viajes-molinetes/resource/51f7cdcf-04dd-40c0-b0b1-32b016d3ab6b/download
Resolving data.buenosaires.gob.ar (data.buenosaires.gob.ar)... 200.16.89.208
Connecting to data.buenosaires.gob.ar (data.buenosaires.gob.ar)|200.16.89.208|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://cdn.buenosaires.gob.ar/datosabiertos/datasets/sbase/subte-viajes-molinetes/molinetes-2022.zip [following]
--2026-06-05 03:09:30--  https://cdn.buenosaires.gob.ar/datosabiertos/datasets/sbase/subte-viajes-molinetes/molinetes-2022.zip
Resolving cdn.buenosaires.gob.ar (cdn.buenosaires.gob.ar)... 200.16.89.97
Connecting to cdn.buenosaires.gob.ar (cdn.buenosaires.gob.ar)|200.16.89.97|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 82535697 (79M) [application/zip]
Saving to: ‘/content/downloads/molinetes_2022.zip’

            /conten  34%[=====>              ]  27.29M   411KB/s    eta 2m 8s  ^C
--2026-06-05 03:10:40--  https://data.buenosaires.gob.ar/dataset/subte-viajes-molinetes/resource/8d752670-38d0-49f6-b6df-0d9948c5e993/download
Resolving data.buenosaires.gob.ar (data.buenosaires.gob.ar)... 200.16.89.208
Connecting to data.buenosaires.gob.ar (data.buenosaires.gob.ar)|200.16.89.208|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://cdn.buenosaires.gob.ar/datosabiertos/datasets/sbase/subte-viajes-molinetes/molinetes-2023.zip [following]
--2026-06-05 03:10:41--  https://cdn.buenosaires.gob.ar/datosabiertos/datasets/sbase/subte-viajes-molinetes/molinetes-2023.zip
Resolving cdn.buenosaires.gob.ar (cdn.buenosaires.gob.ar)... 200.16.89.97
Connecting to cdn.buenosaires.gob.ar (cdn.buenosaires.gob.ar)|200.16.89.97|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 82679537 (79M) [application/zip]
Saving to: ‘/content/downloads/molinetes_2023.zip’

         /content/d   0%[                    ]  50.02K   163KB/s               ^C
--2026-06-05 03:10:42--  https://data.buenosaires.gob.ar/dataset/subte-viajes-molinetes/resource/9faf4137-63c9-4f15-848c-248c166b54ea/download
Resolving data.buenosaires.gob.ar (data.buenosaires.gob.ar)... 200.16.89.208
Connecting to data.buenosaires.gob.ar (data.buenosaires.gob.ar)|200.16.89.208|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://cdn.buenosaires.gob.ar/datosabiertos/datasets/sbase/subte-viajes-molinetes/molinetes-2024.zip [following]
--2026-06-05 03:10:43--  https://cdn.buenosaires.gob.ar/datosabiertos/datasets/sbase/subte-viajes-molinetes/molinetes-2024.zip
Resolving cdn.buenosaires.gob.ar (cdn.buenosaires.gob.ar)... 200.16.89.97
Connecting to cdn.buenosaires.gob.ar (cdn.buenosaires.gob.ar)|200.16.89.97|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 78515314 (75M) [application/zip]
Saving to: ‘/content/downloads/molinetes_2024.zip’

ontent/downloads/mo   1%[                    ]   1.39M   412KB/s    eta 3m 15s ^C
--2026-06-05 03:10:48--  https://data.buenosaires.gob.ar/dataset/subte-viajes-molinetes/resource/0d689701-9efd-4644-85d0-f6a1504509f1/download
Resolving data.buenosaires.gob.ar (data.buenosaires.gob.ar)... 200.16.89.208
Connecting to data.buenosaires.gob.ar (data.buenosaires.gob.ar)|200.16.89.208|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://cdn.buenosaires.gob.ar/datosabiertos/datasets/sbase/subte-viajes-molinetes/molinetes-2025.zip [following]
--2026-06-05 03:10:49--  https://cdn.buenosaires.gob.ar/datosabiertos/datasets/sbase/subte-viajes-molinetes/molinetes-2025.zip
Resolving cdn.buenosaires.gob.ar (cdn.buenosaires.gob.ar)... 200.16.89.97
Connecting to cdn.buenosaires.gob.ar (cdn.buenosaires.gob.ar)|200.16.89.97|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 82361072 (79M) [application/zip]
Saving to: ‘/content/downloads/molinetes_2025.zip’

_2025.zip             5%[>                   ]   4.61M   414KB/s    eta 3m 6s  ^C

In [ ]:
!mkdir -p csv_temp

!unzip "downloads/*.zip" -d csv_temp

Archive:  downloads/molinetes-2025.zip
   creating: csv_temp/molinetes-2025/
  inflating: csv_temp/molinetes-2025/202501_PAX15min-ABC-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202501_PAX15min-DEH-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202502_PAX15min-ABC-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202502_PAX15min-DEH-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202503_PAX15min-ABC-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202503_PAX15min-DEH-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202504_PAX15min-ABC-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202504_PAX15min-DEH-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202505_PAX15min-ABC-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202505_PAX15min-DEH-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202506_PAX15min-ABC-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202506_PAX15min-DEH-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202506_PAX15min-PM-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202507_PAX15min-ABC-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202507_PAX15min-DEH-INCLUYEOTROMODOSDEPAGO (1).csv
  inflating: csv_temp/molinetes-2025/202507_PAX15min-PM-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202508_PAX15min-ABC-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202508_PAX15min-DEH-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202509_PAX15min-ABC-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202509_PAX15min-DEH-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202510_PAX15min-ABC-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202510_PAX15min-DEH-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202511_PAX15min-ABC-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202511_PAX15min-DEH-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202512_PAX15min-ABC-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/molinetes-2025/202512_PAX15min-DEH-INCLUYEOTROMODOSDEPAGO.csv

Archive:  downloads/molinetes-2023.zip
  inflating: csv_temp/202301_PAX15min-ABC.csv
  inflating: csv_temp/202301_PAX15min-DEH.csv
  inflating: csv_temp/202302_PAX15min-ABC.csv
  inflating: csv_temp/202302_PAX15min-DEH.csv
  inflating: csv_temp/202303_PAX15min-ABC.csv
  inflating: csv_temp/202303_PAX15min-DEH.csv
  inflating: csv_temp/202304_PAX15min-ABC.csv
  inflating: csv_temp/202304_PAX15min-DEH.csv
  inflating: csv_temp/202305_PAX15min-ABC.csv
  inflating: csv_temp/202305_PAX15min-DEH.csv
  inflating: csv_temp/202306_PAX15min-ABC.csv
  inflating: csv_temp/202306_PAX15min-DEH.csv
  inflating: csv_temp/202307_PAX15min-ABC.csv
  inflating: csv_temp/202307_PAX15min-DEH.csv
  inflating: csv_temp/202308_PAX15min-ABC.csv
  inflating: csv_temp/202308_PAX15min-DEH.csv
  inflating: csv_temp/202309_PAX15min-ABC.csv
  inflating: csv_temp/202309_PAX15min-DEH.csv
  inflating: csv_temp/202310_PAX15min-ABC.csv
  inflating: csv_temp/202310_PAX15min-DEH.csv
  inflating: csv_temp/202311_PAX15min-ABC.csv
  inflating: csv_temp/202311_PAX15min-DEH.csv
  inflating: csv_temp/202312_PAX15min-ABC.csv
  inflating: csv_temp/202312_PAX15min-DEH.csv

Archive:  downloads/molinetes-2022.zip
  inflating: csv_temp/202201_PAX15min-ABC.csv
  inflating: csv_temp/202201_PAX15min-DEH.csv
  inflating: csv_temp/202202_PAX15min-ABC.csv
  inflating: csv_temp/202202_PAX15min-DEH.csv
  inflating: csv_temp/202203_PAX15min-ABC.csv
  inflating: csv_temp/202203_PAX15min-DEH.csv
  inflating: csv_temp/202204_PAX15min-ABC.csv
  inflating: csv_temp/202204_PAX15min-DEH.csv
  inflating: csv_temp/202205_PAX15min-ABC.csv
  inflating: csv_temp/202205_PAX15min-DEH.csv
  inflating: csv_temp/202206_PAX15min-ABC.csv
  inflating: csv_temp/202206_PAX15min-DEH.csv
  inflating: csv_temp/202207_PAX15min-ABC.csv
  inflating: csv_temp/202207_PAX15min-DEH.csv
  inflating: csv_temp/202208_PAX15min-ABC.csv
  inflating: csv_temp/202208_PAX15min-DEH.csv
  inflating: csv_temp/202209_PAX15min-ABC.csv
  inflating: csv_temp/202209_PAX15min-DEH.csv
  inflating: csv_temp/202210_PAX15min-ABC.csv
  inflating: csv_temp/202210_PAX15min-DEH.csv
  inflating: csv_temp/202211_PAX15min-ABC.csv
  inflating: csv_temp/202211_PAX15min-DEH.csv
  inflating: csv_temp/202212_PAX15min-ABC.csv
  inflating: csv_temp/202212_PAX15min-DEH.csv

Archive:  downloads/molinetes-2024.zip
  inflating: csv_temp/202401_PAX15min-ABC.csv
  inflating: csv_temp/202401_PAX15min-DEH.csv
  inflating: csv_temp/202402_PAX15min-ABC.csv
  inflating: csv_temp/202402_PAX15min-DEH.csv
  inflating: csv_temp/202403_PAX15min-ABC.csv
  inflating: csv_temp/202403_PAX15min-DEH.csv
  inflating: csv_temp/202404_PAX15min-ABC.csv
  inflating: csv_temp/202404_PAX15min-DEH.csv
  inflating: csv_temp/202405_PAX15min-ABC.csv
  inflating: csv_temp/202405_PAX15min-DEH.csv
  inflating: csv_temp/202406_PAX15min-ABC.csv
  inflating: csv_temp/202406_PAX15min-DEH.csv
  inflating: csv_temp/202407_PAX15min-ABC.csv
  inflating: csv_temp/202407_PAX15min-DEH.csv
  inflating: csv_temp/202408_PAX15min-ABC.csv
  inflating: csv_temp/202408_PAX15min-DEH.csv
  inflating: csv_temp/202409_PAX15min-ABC.csv
  inflating: csv_temp/202409_PAX15min-DEH.csv
  inflating: csv_temp/202410_PAX15min-ABC.csv
  inflating: csv_temp/202410_PAX15min-DEH.csv
  inflating: csv_temp/202411_PAX15min-ABC.csv
  inflating: csv_temp/202411_PAX15min-DEH.csv
  inflating: csv_temp/202412_PAX15min-ABC-INCLUYEOTROMODOSDEPAGO.csv
  inflating: csv_temp/202412_PAX15min-DEH-INCLUYEOTROMODOSDEPAGO.csv

4 archives were successfully processed.

In [ ]:
def procesar_y_convertir_a_parquet(path_csv, carpeta_destino="data_parquet"):
    if not os.path.exists(carpeta_destino):
        os.makedirs(carpeta_destino)

    df_raw = pl.read_csv(
        path_csv,
        has_header=False,
        separator="\x00",
        quote_char=None,
        new_columns=["linea_sucia"]
    )

    df_limpio = (
        df_raw.select(
            pl.col("linea_sucia")
            .str.strip_chars('"')
            .str.replace_all(r";+$", "")
            .str.split(";")
            # Ahora sí usamos el parámetro que pide tu versión de Polars
            .list.to_struct(fields=[f"col_{i}" for i in range(10)])
        )
        .unnest("linea_sucia")
    )

    nombres_columnas = df_limpio.row(0)
    df_final = df_limpio.slice(1).rename({
        # Mapeamos los nombres temporales a los reales del header
        f"col_{i}": str(nombre) for i, nombre in enumerate(nombres_columnas)
    })

    nombre_archivo = os.path.basename(path_csv).replace(".csv", ".parquet")
    path_salida = os.path.join(carpeta_destino, nombre_archivo)

    df_final.write_parquet(path_salida)
    return path_salida

# Ejecutamos el loop
archivos_csv = glob.glob("/content/csv_temp/*.csv")
for f in archivos_csv:
    try:
        procesar_y_convertir_a_parquet(f)
        print(f"✅ {f} convertido a Parquet.")
    except Exception as e:
        print(f"❌ Error en {f}: {e}")

❌ Error en /content/csv_temp/202202_PAX15min-DEH.csv: invalid utf-8 sequence
✅ /content/csv_temp/202308_PAX15min-DEH.csv convertido a Parquet.
❌ Error en /content/csv_temp/202403_PAX15min-DEH.csv: invalid utf-8 sequence
✅ /content/csv_temp/202307_PAX15min-DEH.csv convertido a Parquet.
❌ Error en /content/csv_temp/202207_PAX15min-ABC.csv: invalid utf-8 sequence
✅ /content/csv_temp/202305_PAX15min-DEH.csv convertido a Parquet.
❌ Error en /content/csv_temp/202202_PAX15min-ABC.csv: invalid utf-8 sequence
✅ /content/csv_temp/202301_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202312_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202312_PAX15min-DEH.csv convertido a Parquet.
❌ Error en /content/csv_temp/202205_PAX15min-ABC.csv: invalid utf-8 sequence
✅ /content/csv_temp/202311_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202303_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202306_PAX15min-DEH.csv convertido a Parquet.
✅ /content/csv_temp/202406_PAX15min-DEH.csv convertido a Parquet.
❌ Error en /content/csv_temp/202201_PAX15min-ABC.csv: invalid utf-8 sequence
❌ Error en /content/csv_temp/202204_PAX15min-ABC.csv: invalid utf-8 sequence
✅ /content/csv_temp/202207_PAX15min-DEH.csv convertido a Parquet.
✅ /content/csv_temp/202410_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202209_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202411_PAX15min-DEH.csv convertido a Parquet.
✅ /content/csv_temp/202407_PAX15min-DEH.csv convertido a Parquet.
✅ /content/csv_temp/202409_PAX15min-DEH.csv convertido a Parquet.
✅ /content/csv_temp/202301_PAX15min-DEH.csv convertido a Parquet.
❌ Error en /content/csv_temp/202208_PAX15min-ABC.csv: invalid utf-8 sequence
✅ /content/csv_temp/202212_PAX15min-DEH.csv convertido a Parquet.
❌ Error en /content/csv_temp/202405_PAX15min-DEH.csv: invalid utf-8 sequence
❌ Error en /content/csv_temp/202210_PAX15min-DEH.csv: invalid utf-8 sequence
❌ Error en /content/csv_temp/202210_PAX15min-ABC.csv: invalid utf-8 sequence
❌ Error en /content/csv_temp/202203_PAX15min-DEH.csv: invalid utf-8 sequence
✅ /content/csv_temp/202303_PAX15min-DEH.csv convertido a Parquet.
❌ Error en /content/csv_temp/202205_PAX15min-DEH.csv: invalid utf-8 sequence
❌ Error en /content/csv_temp/202201_PAX15min-DEH.csv: invalid utf-8 sequence
✅ /content/csv_temp/202408_PAX15min-DEH.csv convertido a Parquet.
✅ /content/csv_temp/202309_PAX15min-DEH.csv convertido a Parquet.
✅ /content/csv_temp/202304_PAX15min-ABC.csv convertido a Parquet.
❌ Error en /content/csv_temp/202405_PAX15min-ABC.csv: invalid utf-8 sequence
✅ /content/csv_temp/202406_PAX15min-ABC.csv convertido a Parquet.
❌ Error en /content/csv_temp/202208_PAX15min-DEH.csv: invalid utf-8 sequence
✅ /content/csv_temp/202411_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202309_PAX15min-ABC.csv convertido a Parquet.
❌ Error en /content/csv_temp/202206_PAX15min-ABC.csv: invalid utf-8 sequence
✅ /content/csv_temp/202401_PAX15min-ABC.csv convertido a Parquet.
❌ Error en /content/csv_temp/202209_PAX15min-DEH.csv: invalid utf-8 sequence
✅ /content/csv_temp/202412_PAX15min-ABC-INCLUYEOTROMODOSDEPAGO.csv convertido a Parquet.
✅ /content/csv_temp/202407_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202310_PAX15min-DEH.csv convertido a Parquet.
❌ Error en /content/csv_temp/202203_PAX15min-ABC.csv: invalid utf-8 sequence
✅ /content/csv_temp/202409_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202311_PAX15min-DEH.csv convertido a Parquet.
✅ /content/csv_temp/202412_PAX15min-DEH-INCLUYEOTROMODOSDEPAGO.csv convertido a Parquet.
✅ /content/csv_temp/202306_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202302_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202410_PAX15min-DEH.csv convertido a Parquet.
❌ Error en /content/csv_temp/202403_PAX15min-ABC.csv: invalid utf-8 sequence
✅ /content/csv_temp/202310_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202305_PAX15min-ABC.csv convertido a Parquet.
❌ Error en /content/csv_temp/202206_PAX15min-DEH.csv: invalid utf-8 sequence
✅ /content/csv_temp/202408_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202212_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202308_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202307_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202402_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202304_PAX15min-DEH.csv convertido a Parquet.
✅ /content/csv_temp/202402_PAX15min-DEH.csv convertido a Parquet.
✅ /content/csv_temp/202401_PAX15min-DEH.csv convertido a Parquet.
✅ /content/csv_temp/202302_PAX15min-DEH.csv convertido a Parquet.
✅ /content/csv_temp/202211_PAX15min-ABC.csv convertido a Parquet.
✅ /content/csv_temp/202204_PAX15min-DEH.csv convertido a Parquet.
❌ Error en /content/csv_temp/202404_PAX15min-ABC.csv: invalid utf-8 sequence
✅ /content/csv_temp/202211_PAX15min-DEH.csv convertido a Parquet.
❌ Error en /content/csv_temp/202404_PAX15min-DEH.csv: invalid utf-8 sequence

In [ ]:
# Escanea todos los archivos al instante sin necesidad de unirlos físicamente
df_master = pl.scan_parquet("data_parquet/*.parquet")

In [ ]:
df_master.head(1000000).collect()

shape: (1_000_000, 10)
┌──────────┬──────────┬──────────┬────────┬───┬───────────┬────────────────┬───────────┬───────────┐
│ FECHA    ┆ DESDE    ┆ HASTA    ┆ LINEA  ┆ … ┆ pax_pagos ┆ pax_pases_pago ┆ pax_franq ┆ pax_TOTAL │
│ ---      ┆ ---      ┆ ---      ┆ ---    ┆   ┆ ---       ┆ s              ┆ ---       ┆ ---       │
│ str      ┆ str      ┆ str      ┆ str    ┆   ┆ str       ┆ ---            ┆ str       ┆ str       │
│          ┆          ┆          ┆        ┆   ┆           ┆ str            ┆           ┆           │
╞══════════╪══════════╪══════════╪════════╪═══╪═══════════╪════════════════╪═══════════╪═══════════╡
│ 1/4/2022 ┆ 05:15:00 ┆ 05:30:00 ┆ LineaD ┆ … ┆ 0         ┆ 0              ┆ 1         ┆ 1         │
│ 1/4/2022 ┆ 05:15:00 ┆ 05:30:00 ┆ LineaD ┆ … ┆ 0         ┆ 0              ┆ 1         ┆ 1         │
│ 1/4/2022 ┆ 05:15:00 ┆ 05:30:00 ┆ LineaD ┆ … ┆ 4         ┆ 0              ┆ 0         ┆ 4         │
│ 1/4/2022 ┆ 05:15:00 ┆ 05:30:00 ┆ LineaD ┆ … ┆ 2         ┆ 0              ┆ 1         ┆ 3         │
│ 1/4/2022 ┆ 05:15:00 ┆ 05:30:00 ┆ LineaE ┆ … ┆ 1         ┆ 0              ┆ 0         ┆ 1         │
│ …        ┆ …        ┆ …        ┆ …      ┆ … ┆ …         ┆ …              ┆ …         ┆ …         │
│ 6/9/2022 ┆ 17:45:00 ┆ 18:00:00 ┆ LineaC ┆ … ┆ 3         ┆ 1              ┆ 1         ┆ 5         │
│ 6/9/2022 ┆ 17:45:00 ┆ 18:00:00 ┆ LineaC ┆ … ┆ 21        ┆ 0              ┆ 0         ┆ 21        │
│ 6/9/2022 ┆ 17:45:00 ┆ 18:00:00 ┆ LineaC ┆ … ┆ 32        ┆ 0              ┆ 0         ┆ 32        │
│ 6/9/2022 ┆ 17:45:00 ┆ 18:00:00 ┆ LineaC ┆ … ┆ 58        ┆ 0              ┆ 1         ┆ 59        │
│ 6/9/2022 ┆ 17:45:00 ┆ 18:00:00 ┆ LineaA ┆ … ┆ 62        ┆ 0              ┆ 2         ┆ 64        │
└──────────┴──────────┴──────────┴────────┴───┴───────────┴────────────────┴───────────┴───────────┘

In [ ]:
print(df_master.select(pl.len()))

naive plan: (run LazyFrame.explain(optimized=True) to see the optimized plan)

SELECT [len()]
  Parquet SCAN [data_parquet/202204_PAX15min-DEH.parquet, ... 48 other sources]
  PROJECT */10 COLUMNS
  ESTIMATED ROWS: 21648200

In [ ]:
df_problema = pl.scan_parquet("data_parquet/202311_PAX15min-ABC.parquet")

In [ ]:
df_problema.head(100).collect()

shape: (100, 10)
┌───────────┬──────────┬──────────┬────────┬───┬───────────┬──────────────┬───────────┬────────────┐
│ FECHA     ┆ DESDE    ┆ HASTA    ┆ LINEA  ┆ … ┆ pax_pagos ┆ pax_pases_pa ┆ pax_franq ┆ pax_TOTAL" │
│ ---       ┆ ---      ┆ ---      ┆ ---    ┆   ┆ ---       ┆ gos          ┆ ---       ┆ ---        │
│ str       ┆ str      ┆ str      ┆ str    ┆   ┆ str       ┆ ---          ┆ str       ┆ str        │
│           ┆          ┆          ┆        ┆   ┆           ┆ str          ┆           ┆            │
╞═══════════╪══════════╪══════════╪════════╪═══╪═══════════╪══════════════╪═══════════╪════════════╡
│ 1/11/2023 ┆ 05:15:00 ┆ 05:30:00 ┆ LineaB ┆ … ┆ 8         ┆ 0            ┆ 0         ┆ 8"         │
│ 1/11/2023 ┆ 05:15:00 ┆ 05:30:00 ┆ LineaB ┆ … ┆ 4         ┆ 0            ┆ 0         ┆ 4"         │
│ 1/11/2023 ┆ 05:15:00 ┆ 05:30:00 ┆ LineaB ┆ … ┆ 18        ┆ 0            ┆ 0         ┆ 18"        │
│ 1/11/2023 ┆ 05:15:00 ┆ 05:30:00 ┆ LineaB ┆ … ┆ 1         ┆ 0            ┆ 0         ┆ 1"         │
│ 1/11/2023 ┆ 05:15:00 ┆ 05:30:00 ┆ LineaA ┆ … ┆ 0         ┆ 0            ┆ 2         ┆ 2"         │
│ …         ┆ …        ┆ …        ┆ …      ┆ … ┆ …         ┆ …            ┆ …         ┆ …          │
│ 1/11/2023 ┆ 05:15:00 ┆ 05:30:00 ┆ LineaB ┆ … ┆ 5         ┆ 0            ┆ 1         ┆ 6"         │
│ 1/11/2023 ┆ 05:15:00 ┆ 05:30:00 ┆ LineaA ┆ … ┆ 2         ┆ 0            ┆ 0         ┆ 2"         │
│ 1/11/2023 ┆ 05:15:00 ┆ 05:30:00 ┆ LineaB ┆ … ┆ 8         ┆ 0            ┆ 0         ┆ 8"         │
│ 1/11/2023 ┆ 05:15:00 ┆ 05:30:00 ┆ LineaA ┆ … ┆ 0         ┆ 0            ┆ 1         ┆ 1"         │
│ 1/11/2023 ┆ 05:15:00 ┆ 05:30:00 ┆ LineaB ┆ … ┆ 4         ┆ 0            ┆ 1         ┆ 5"         │
└───────────┴──────────┴──────────┴────────┴───┴───────────┴──────────────┴───────────┴────────────┘